create_clock -period 8.000 -name clk_e -waveform {0.000 4.000} [get_ports clk_e_p]
#create_clock -period 6.400 -name clk_e -waveform {0.000 3.200} [get_ports clk_b_p]


set_property PACKAGE_PIN F22 [get_ports qsfp_a_reset]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp_a_reset]
set_property PACKAGE_PIN BC22 [get_ports qsfp_b_reset]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp_b_reset]
set_property PACKAGE_PIN BA23 [get_ports qsfp_c_reset]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp_c_reset]
set_property PACKAGE_PIN AW23 [get_ports qsfp_d_reset]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp_d_reset]
set_property PACKAGE_PIN B24 [get_ports qsfp_clock_sel]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp_clock_sel]



# from ibert design:



# file: ibert_ultrascale_gty_0.xdc
####################################################################################
##   ____  ____ 
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 2012.3
##  \   \         Application : IBERT Ultrascale
##  /   /         Filename : example_ibert_ultrascale_gty_0.xdc
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\
##
##
## 
## Generated by Xilinx IBERT Ultrascale
##**************************************************************************
##
## Icon Constraints
##
create_clock -name D_CLK -period 6.4 [get_ports gty_sysclkp_i]
set_clock_groups -group [get_clocks D_CLK -include_generated_clocks] -asynchronous

set_property C_CLK_INPUT_FREQ_HZ 156250000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER true [get_debug_cores dbg_hub]
##
##Eye scan 
##
set_property ES_EYE_SCAN_EN TRUE [get_cells u_ibert_gty_core/inst/QUAD[*].u_q/CH[*].u_ch/u_gtye4_channel]
##
##gtrefclk lock constraints
##
set_property PACKAGE_PIN AV13 [get_ports gty_refclk0p_i[0]]
set_property PACKAGE_PIN AV12 [get_ports gty_refclk0n_i[0]]
set_property PACKAGE_PIN AU11 [get_ports gty_refclk1p_i[0]]
set_property PACKAGE_PIN AU10 [get_ports gty_refclk1n_i[0]]
set_property PACKAGE_PIN AT13 [get_ports gty_refclk0p_i[1]]
set_property PACKAGE_PIN AT12 [get_ports gty_refclk0n_i[1]]
set_property PACKAGE_PIN AR11 [get_ports gty_refclk1p_i[1]]
set_property PACKAGE_PIN AR10 [get_ports gty_refclk1n_i[1]]
set_property PACKAGE_PIN AP13 [get_ports gty_refclk0p_i[2]]
set_property PACKAGE_PIN AP12 [get_ports gty_refclk0n_i[2]]
set_property PACKAGE_PIN AN11 [get_ports gty_refclk1p_i[2]]
set_property PACKAGE_PIN AN10 [get_ports gty_refclk1n_i[2]]
set_property PACKAGE_PIN L11 [get_ports gty_refclk0p_i[3]]
set_property PACKAGE_PIN L10 [get_ports gty_refclk0n_i[3]]
set_property PACKAGE_PIN K13 [get_ports gty_refclk1p_i[3]]
set_property PACKAGE_PIN K12 [get_ports gty_refclk1n_i[3]]
##
## Refclk constraints
##
create_clock -name gtrefclk0_18 -period 6.2 [get_ports gty_refclk0p_i[0]]
create_clock -name gtrefclk1_18 -period 6.2 [get_ports gty_refclk1p_i[0]]
set_clock_groups -group [get_clocks gtrefclk0_18 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_18 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_19 -period 6.2 [get_ports gty_refclk0p_i[1]]
create_clock -name gtrefclk1_19 -period 6.2 [get_ports gty_refclk1p_i[1]]
set_clock_groups -group [get_clocks gtrefclk0_19 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_19 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_20 -period 6.2 [get_ports gty_refclk0p_i[2]]
create_clock -name gtrefclk1_20 -period 6.2 [get_ports gty_refclk1p_i[2]]
set_clock_groups -group [get_clocks gtrefclk0_20 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_20 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_29 -period 6.2 [get_ports gty_refclk0p_i[3]]
create_clock -name gtrefclk1_29 -period 6.2 [get_ports gty_refclk1p_i[3]]
set_clock_groups -group [get_clocks gtrefclk0_29 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_29 -include_generated_clocks] -asynchronous
##
## System clock pin locs and timing constraints
##
set_property PACKAGE_PIN BE22 [get_ports gty_sysclkp_i]
set_property IOSTANDARD LVDS [get_ports gty_sysclkp_i]
##
## TX/RX out clock clock constraints
##
# GT X0Y12
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[0].u_q/CH[0].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[0].u_q/CH[0].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y13
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[0].u_q/CH[1].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[0].u_q/CH[1].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y14
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[0].u_q/CH[2].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[0].u_q/CH[2].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y15
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[0].u_q/CH[3].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[0].u_q/CH[3].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y16
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[1].u_q/CH[0].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[1].u_q/CH[0].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y17
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[1].u_q/CH[1].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[1].u_q/CH[1].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y18
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[1].u_q/CH[2].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[1].u_q/CH[2].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y19
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[1].u_q/CH[3].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[1].u_q/CH[3].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y20
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[2].u_q/CH[0].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[2].u_q/CH[0].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y21
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[2].u_q/CH[1].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[2].u_q/CH[1].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y22
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[2].u_q/CH[2].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[2].u_q/CH[2].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y23
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[2].u_q/CH[3].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[2].u_q/CH[3].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y56
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[3].u_q/CH[0].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[3].u_q/CH[0].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y57
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[3].u_q/CH[1].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[3].u_q/CH[1].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y58
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[3].u_q/CH[2].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[3].u_q/CH[2].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y59
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[3].u_q/CH[3].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[3].u_q/CH[3].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]

