create_clock -period 8.000 -name clk_e -waveform {0.000 4.000} [get_ports clk_e_p]

set_property -dict {PACKAGE_PIN A28 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports clk_e_p]
set_property -dict {PACKAGE_PIN A29 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports clk_e_n]

set_property PACKAGE_PIN B22 [get_ports led_cs]
set_property PACKAGE_PIN C23 [get_ports led_din]
set_property PACKAGE_PIN A23 [get_ports led_dout]
set_property PACKAGE_PIN A22 [get_ports led_sclk]
set_property IOSTANDARD LVCMOS18 [get_ports led_cs]
set_property IOSTANDARD LVCMOS18 [get_ports led_din]
set_property IOSTANDARD LVCMOS18 [get_ports led_dout]
set_property IOSTANDARD LVCMOS18 [get_ports led_sclk]

# from ibert design:




# file: ibert_ultrascale_gty_0.xdc
####################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 2012.3
##  \   \         Application : IBERT Ultrascale
##  /   /         Filename : example_ibert_ultrascale_gty_0.xdc
## /___/   / ## \   \  / ##  \___\/\___ ##
##
##
## Generated by Xilinx IBERT Ultrascale
##**************************************************************************
##
## Icon Constraints
##
create_clock -period 6.400 -name D_CLK [get_ports gty_sysclkp_i]
set_clock_groups -asynchronous -group [get_clocks D_CLK -include_generated_clocks]

##
##Eye scan
##
##
##gtrefclk lock constraints
##
set_property PACKAGE_PIN BD40 [get_ports {gty_refclk0n_i[0]}]
set_property PACKAGE_PIN BD39 [get_ports {gty_refclk0p_i[0]}]
set_property PACKAGE_PIN BC42 [get_ports {gty_refclk1n_i[0]}]
set_property PACKAGE_PIN BC41 [get_ports {gty_refclk1p_i[0]}]
set_property PACKAGE_PIN BB40 [get_ports {gty_refclk0n_i[1]}]
set_property PACKAGE_PIN BB39 [get_ports {gty_refclk0p_i[1]}]
set_property PACKAGE_PIN BA42 [get_ports {gty_refclk1n_i[1]}]
set_property PACKAGE_PIN BA41 [get_ports {gty_refclk1p_i[1]}]
set_property PACKAGE_PIN AY40 [get_ports {gty_refclk0n_i[2]}]
set_property PACKAGE_PIN AY39 [get_ports {gty_refclk0p_i[2]}]
set_property PACKAGE_PIN AW42 [get_ports {gty_refclk1n_i[2]}]
set_property PACKAGE_PIN AW41 [get_ports {gty_refclk1p_i[2]}]
set_property PACKAGE_PIN AV40 [get_ports {gty_refclk0n_i[3]}]
set_property PACKAGE_PIN AV39 [get_ports {gty_refclk0p_i[3]}]
set_property PACKAGE_PIN AU42 [get_ports {gty_refclk1n_i[3]}]
set_property PACKAGE_PIN AU41 [get_ports {gty_refclk1p_i[3]}]
set_property PACKAGE_PIN AT40 [get_ports {gty_refclk0n_i[4]}]
set_property PACKAGE_PIN AT39 [get_ports {gty_refclk0p_i[4]}]
set_property PACKAGE_PIN AR42 [get_ports {gty_refclk1n_i[4]}]
set_property PACKAGE_PIN AR41 [get_ports {gty_refclk1p_i[4]}]
set_property PACKAGE_PIN AP40 [get_ports {gty_refclk0n_i[5]}]
set_property PACKAGE_PIN AP39 [get_ports {gty_refclk0p_i[5]}]
set_property PACKAGE_PIN AN42 [get_ports {gty_refclk1n_i[5]}]
set_property PACKAGE_PIN AN41 [get_ports {gty_refclk1p_i[5]}]
set_property PACKAGE_PIN AE42 [get_ports {gty_refclk0n_i[6]}]
set_property PACKAGE_PIN AE41 [get_ports {gty_refclk0p_i[6]}]
set_property PACKAGE_PIN AC42 [get_ports {gty_refclk1n_i[6]}]
set_property PACKAGE_PIN AC41 [get_ports {gty_refclk1p_i[6]}]
set_property PACKAGE_PIN U42 [get_ports {gty_refclk0n_i[7]}]
set_property PACKAGE_PIN U41 [get_ports {gty_refclk0p_i[7]}]
set_property PACKAGE_PIN T40 [get_ports {gty_refclk1n_i[7]}]
set_property PACKAGE_PIN T39 [get_ports {gty_refclk1p_i[7]}]
set_property PACKAGE_PIN BD12 [get_ports {gty_refclk0n_i[8]}]
set_property PACKAGE_PIN BD13 [get_ports {gty_refclk0p_i[8]}]
set_property PACKAGE_PIN BC10 [get_ports {gty_refclk1n_i[8]}]
set_property PACKAGE_PIN BC11 [get_ports {gty_refclk1p_i[8]}]
set_property PACKAGE_PIN BB12 [get_ports {gty_refclk0n_i[9]}]
set_property PACKAGE_PIN BB13 [get_ports {gty_refclk0p_i[9]}]
set_property PACKAGE_PIN BA11 [get_ports {gty_refclk1p_i[9]}]
set_property PACKAGE_PIN BA10 [get_ports {gty_refclk1n_i[9]}]
set_property PACKAGE_PIN AY12 [get_ports {gty_refclk0n_i[10]}]
set_property PACKAGE_PIN AY13 [get_ports {gty_refclk0p_i[10]}]
set_property PACKAGE_PIN AW10 [get_ports {gty_refclk1n_i[10]}]
set_property PACKAGE_PIN AW11 [get_ports {gty_refclk1p_i[10]}]
set_property PACKAGE_PIN AV12 [get_ports {gty_refclk0n_i[11]}]
set_property PACKAGE_PIN AV13 [get_ports {gty_refclk0p_i[11]}]
set_property PACKAGE_PIN AU10 [get_ports {gty_refclk1n_i[11]}]
set_property PACKAGE_PIN AU11 [get_ports {gty_refclk1p_i[11]}]
set_property PACKAGE_PIN AT12 [get_ports {gty_refclk0n_i[12]}]
set_property PACKAGE_PIN AT13 [get_ports {gty_refclk0p_i[12]}]
set_property PACKAGE_PIN AR10 [get_ports {gty_refclk1n_i[12]}]
set_property PACKAGE_PIN AR11 [get_ports {gty_refclk1p_i[12]}]
set_property PACKAGE_PIN AP12 [get_ports {gty_refclk0n_i[13]}]
set_property PACKAGE_PIN AP13 [get_ports {gty_refclk0p_i[13]}]
set_property PACKAGE_PIN AN10 [get_ports {gty_refclk1n_i[13]}]
set_property PACKAGE_PIN AN11 [get_ports {gty_refclk1p_i[13]}]
set_property PACKAGE_PIN AE10 [get_ports {gty_refclk0n_i[14]}]
set_property PACKAGE_PIN AE11 [get_ports {gty_refclk0p_i[14]}]
set_property PACKAGE_PIN AC10 [get_ports {gty_refclk1n_i[14]}]
set_property PACKAGE_PIN AC11 [get_ports {gty_refclk1p_i[14]}]
set_property PACKAGE_PIN R10 [get_ports {gty_refclk0n_i[15]}]
set_property PACKAGE_PIN R11 [get_ports {gty_refclk0p_i[15]}]
set_property PACKAGE_PIN P12 [get_ports {gty_refclk1n_i[15]}]
set_property PACKAGE_PIN P13 [get_ports {gty_refclk1p_i[15]}]
set_property PACKAGE_PIN L10 [get_ports {gty_refclk0n_i[16]}]
set_property PACKAGE_PIN L11 [get_ports {gty_refclk0p_i[16]}]
set_property PACKAGE_PIN K12 [get_ports {gty_refclk1n_i[16]}]
set_property PACKAGE_PIN K13 [get_ports {gty_refclk1p_i[16]}]
##
## Refclk constraints
##
create_clock -period 6.200 -name gtrefclk0_0 [get_ports {gty_refclk0p_i[0]}]
create_clock -period 6.200 -name gtrefclk1_0 [get_ports {gty_refclk1p_i[0]}]
set_clock_groups -asynchronous -group [get_clocks gtrefclk0_0 -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks gtrefclk1_0 -include_generated_clocks]
create_clock -period 6.200 -name gtrefclk0_1 [get_ports {gty_refclk0p_i[1]}]
create_clock -period 6.200 -name gtrefclk1_1 [get_ports {gty_refclk1p_i[1]}]
set_clock_groups -asynchronous -group [get_clocks gtrefclk0_1 -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks gtrefclk1_1 -include_generated_clocks]
create_clock -period 6.200 -name gtrefclk0_2 [get_ports {gty_refclk0p_i[2]}]
create_clock -period 6.200 -name gtrefclk1_2 [get_ports {gty_refclk1p_i[2]}]
set_clock_groups -asynchronous -group [get_clocks gtrefclk0_2 -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks gtrefclk1_2 -include_generated_clocks]
create_clock -period 6.200 -name gtrefclk0_3 [get_ports {gty_refclk0p_i[3]}]
create_clock -period 6.200 -name gtrefclk1_3 [get_ports {gty_refclk1p_i[3]}]
set_clock_groups -asynchronous -group [get_clocks gtrefclk0_3 -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks gtrefclk1_3 -include_generated_clocks]
create_clock -period 6.200 -name gtrefclk0_4 [get_ports {gty_refclk0p_i[4]}]
create_clock -period 6.200 -name gtrefclk1_4 [get_ports {gty_refclk1p_i[4]}]
set_clock_groups -asynchronous -group [get_clocks gtrefclk0_4 -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks gtrefclk1_4 -include_generated_clocks]
create_clock -period 6.200 -name gtrefclk0_5 [get_ports {gty_refclk0p_i[5]}]
create_clock -period 6.200 -name gtrefclk1_5 [get_ports {gty_refclk1p_i[5]}]
set_clock_groups -asynchronous -group [get_clocks gtrefclk0_5 -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks gtrefclk1_5 -include_generated_clocks]
create_clock -period 8.000 -name gtrefclk0_8 [get_ports {gty_refclk0p_i[6]}]
create_clock -period 8.000 -name gtrefclk1_8 [get_ports {gty_refclk1p_i[6]}]
set_clock_groups -asynchronous -group [get_clocks gtrefclk0_8 -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks gtrefclk1_8 -include_generated_clocks]
create_clock -period 8.000 -name gtrefclk0_11 [get_ports {gty_refclk0p_i[7]}]
create_clock -period 8.000 -name gtrefclk1_11 [get_ports {gty_refclk1p_i[7]}]
set_clock_groups -asynchronous -group [get_clocks gtrefclk0_11 -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks gtrefclk1_11 -include_generated_clocks]
create_clock -period 6.200 -name gtrefclk0_15 [get_ports {gty_refclk0p_i[8]}]
create_clock -period 6.200 -name gtrefclk1_15 [get_ports {gty_refclk1p_i[8]}]
set_clock_groups -asynchronous -group [get_clocks gtrefclk0_15 -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks gtrefclk1_15 -include_generated_clocks]
create_clock -period 6.200 -name gtrefclk0_16 [get_ports {gty_refclk0p_i[9]}]
create_clock -period 6.200 -name gtrefclk1_16 [get_ports {gty_refclk1p_i[9]}]
set_clock_groups -asynchronous -group [get_clocks gtrefclk0_16 -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks gtrefclk1_16 -include_generated_clocks]
create_clock -period 6.200 -name gtrefclk0_17 [get_ports {gty_refclk0p_i[10]}]
create_clock -period 6.200 -name gtrefclk1_17 [get_ports {gty_refclk1p_i[10]}]
set_clock_groups -asynchronous -group [get_clocks gtrefclk0_17 -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks gtrefclk1_17 -include_generated_clocks]
create_clock -period 6.200 -name gtrefclk0_18 [get_ports {gty_refclk0p_i[11]}]
create_clock -period 6.200 -name gtrefclk1_18 [get_ports {gty_refclk1p_i[11]}]
set_clock_groups -asynchronous -group [get_clocks gtrefclk0_18 -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks gtrefclk1_18 -include_generated_clocks]
create_clock -period 6.200 -name gtrefclk0_19 [get_ports {gty_refclk0p_i[12]}]
create_clock -period 6.200 -name gtrefclk1_19 [get_ports {gty_refclk1p_i[12]}]
set_clock_groups -asynchronous -group [get_clocks gtrefclk0_19 -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks gtrefclk1_19 -include_generated_clocks]
create_clock -period 6.200 -name gtrefclk0_20 [get_ports {gty_refclk0p_i[13]}]
create_clock -period 6.200 -name gtrefclk1_20 [get_ports {gty_refclk1p_i[13]}]
set_clock_groups -asynchronous -group [get_clocks gtrefclk0_20 -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks gtrefclk1_20 -include_generated_clocks]
create_clock -period 8.000 -name gtrefclk0_23 [get_ports {gty_refclk0p_i[14]}]
create_clock -period 8.000 -name gtrefclk1_23 [get_ports {gty_refclk1p_i[14]}]
set_clock_groups -asynchronous -group [get_clocks gtrefclk0_23 -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks gtrefclk1_23 -include_generated_clocks]
create_clock -period 8.000 -name gtrefclk0_27 [get_ports {gty_refclk0p_i[15]}]
create_clock -period 8.000 -name gtrefclk1_27 [get_ports {gty_refclk1p_i[15]}]
set_clock_groups -asynchronous -group [get_clocks gtrefclk0_27 -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks gtrefclk1_27 -include_generated_clocks]
create_clock -period 6.200 -name gtrefclk0_29 [get_ports {gty_refclk0p_i[16]}]
create_clock -period 6.200 -name gtrefclk1_29 [get_ports {gty_refclk1p_i[16]}]
set_clock_groups -asynchronous -group [get_clocks gtrefclk0_29 -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks gtrefclk1_29 -include_generated_clocks]
##
## System clock pin locs and timing constraints
##
set_property PACKAGE_PIN BE22 [get_ports gty_sysclkp_i]
set_property IOSTANDARD LVDS [get_ports gty_sysclkp_i]
##
## TX/RX out clock clock constraints
##
# GT X0Y0
# GT X0Y1
# GT X0Y2
# GT X0Y3
# GT X0Y4
# GT X0Y5
# GT X0Y6
# GT X0Y7
# GT X0Y8
# GT X0Y9
# GT X0Y10
# GT X0Y11
# GT X0Y12
# GT X0Y13
# GT X0Y14
# GT X0Y15
# GT X0Y16
# GT X0Y17
# GT X0Y18
# GT X0Y19
# GT X0Y20
# GT X0Y21
# GT X0Y22
# GT X0Y23
# GT X0Y24
# GT X0Y25
# GT X0Y26
# GT X0Y27
# GT X0Y28
# GT X0Y29
# GT X0Y30
# GT X0Y31
# GT X0Y32
# GT X0Y33
# GT X0Y34
# GT X0Y35
# GT X0Y36
# GT X0Y37
# GT X0Y38
# GT X0Y39
# GT X0Y40
# GT X0Y41
# GT X0Y42
# GT X0Y43
# GT X0Y44
# GT X0Y45
# GT X0Y46
# GT X0Y47
# GT X0Y48
# GT X0Y49
# GT X0Y50
# GT X0Y51
# GT X0Y52
# GT X0Y53
# GT X0Y54
# GT X0Y55
# GT X0Y0
# GT X0Y1
# GT X0Y2
# GT X0Y3
# GT X0Y4
# GT X0Y5
# GT X0Y6
# GT X0Y7
# GT X0Y8
# GT X0Y9
# GT X0Y10
# GT X0Y11
# GT X0Y12
# GT X0Y13
# GT X0Y14
# GT X0Y15
# GT X0Y16
# GT X0Y17
# GT X0Y18
# GT X0Y19
# GT X0Y20
# GT X0Y21
# GT X0Y22
# GT X0Y23
# GT X0Y24
# GT X0Y25
# GT X0Y26
# GT X0Y27
# GT X0Y28
# GT X0Y29
# GT X0Y30
# GT X0Y31
# GT X0Y32
# GT X0Y33
# GT X0Y34
# GT X0Y35
# GT X0Y36
# GT X0Y37
# GT X0Y38
# GT X0Y39
# GT X0Y40
# GT X0Y41
# GT X0Y42
# GT X0Y43
# GT X0Y44
# GT X0Y45
# GT X0Y46
# GT X0Y47
# GT X0Y48
# GT X0Y49
# GT X0Y50
# GT X0Y51
# GT X0Y52
# GT X0Y53
# GT X0Y54
# GT X0Y55
# GT X0Y56
# GT X0Y57
# GT X0Y58
# GT X0Y59

set_property PACKAGE_PIN F22 [get_ports qsfp_a_reset]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp_a_reset]
set_property PACKAGE_PIN BC22 [get_ports qsfp_b_reset]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp_b_reset]
set_property PACKAGE_PIN BA23 [get_ports qsfp_c_reset]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp_c_reset]
set_property PACKAGE_PIN AW23 [get_ports qsfp_d_reset]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp_d_reset]
set_property PACKAGE_PIN B24 [get_ports qsfp_clock_sel]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp_clock_sel]
set_property C_CLK_INPUT_FREQ_HZ 156250000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER true [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
