set_property PACKAGE_PIN AT32 [get_ports {GPIOLED[0]}]
set_property PACKAGE_PIN AV34 [get_ports {GPIOLED[1]}]
set_property PACKAGE_PIN AY30 [get_ports {GPIOLED[2]}]
set_property PACKAGE_PIN BB32 [get_ports {GPIOLED[3]}]
set_property PACKAGE_PIN BF32 [get_ports {GPIOLED[4]}]
set_property PACKAGE_PIN AV36 [get_ports {GPIOLED[5]}]
set_property PACKAGE_PIN AY35 [get_ports {GPIOLED[6]}]
set_property PACKAGE_PIN BA37 [get_ports {GPIOLED[7]}]
set_property PACKAGE_PIN BC9 [get_ports CLK_p]

set_property IOSTANDARD LVCMOS12 [get_ports {GPIOLED[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports {GPIOLED[1]}]
set_property IOSTANDARD LVCMOS12 [get_ports {GPIOLED[2]}]
set_property IOSTANDARD LVCMOS12 [get_ports {GPIOLED[3]}]
set_property IOSTANDARD LVCMOS12 [get_ports {GPIOLED[4]}]
set_property IOSTANDARD LVCMOS12 [get_ports {GPIOLED[5]}]
set_property IOSTANDARD LVCMOS12 [get_ports {GPIOLED[6]}]
set_property IOSTANDARD LVCMOS12 [get_ports {GPIOLED[7]}]
set_property IOSTANDARD LVDS [get_ports CLK_p]


