
# file: ibert_ultrascale_gty_0.xdc
####################################################################################
##   ____  ____ 
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 2012.3
##  \   \         Application : IBERT Ultrascale
##  /   /         Filename : example_ibert_ultrascale_gty_0.xdc
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\
##
##
## 
## Generated by Xilinx IBERT Ultrascale
##**************************************************************************
##
## Icon Constraints
##

set_property C_CLK_INPUT_FREQ_HZ 161132812 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER true [get_debug_cores dbg_hub]
##
##gtrefclk lock constraints
##
set_property PACKAGE_PIN AV39 [get_ports gty_refclk0p_i[0]]
set_property PACKAGE_PIN AV40 [get_ports gty_refclk0n_i[0]]
set_property PACKAGE_PIN AU41 [get_ports gty_refclk1p_i[0]]
set_property PACKAGE_PIN AU42 [get_ports gty_refclk1n_i[0]]
set_property PACKAGE_PIN AP39 [get_ports gty_refclk0p_i[1]]
set_property PACKAGE_PIN AP40 [get_ports gty_refclk0n_i[1]]
set_property PACKAGE_PIN AN41 [get_ports gty_refclk1p_i[1]]
set_property PACKAGE_PIN AN42 [get_ports gty_refclk1n_i[1]]
set_property PACKAGE_PIN AM39 [get_ports gty_refclk0p_i[2]]
set_property PACKAGE_PIN AM40 [get_ports gty_refclk0n_i[2]]
set_property PACKAGE_PIN AL41 [get_ports gty_refclk1p_i[2]]
set_property PACKAGE_PIN AL42 [get_ports gty_refclk1n_i[2]]
set_property PACKAGE_PIN AJ41 [get_ports gty_refclk0p_i[3]]
set_property PACKAGE_PIN AJ42 [get_ports gty_refclk0n_i[3]]
set_property PACKAGE_PIN AG41 [get_ports gty_refclk1p_i[3]]
set_property PACKAGE_PIN AG42 [get_ports gty_refclk1n_i[3]]
set_property PACKAGE_PIN BB13 [get_ports gty_refclk0p_i[4]]
set_property PACKAGE_PIN BB12 [get_ports gty_refclk0n_i[4]]
set_property PACKAGE_PIN BA11 [get_ports gty_refclk1p_i[4]]
set_property PACKAGE_PIN BA10 [get_ports gty_refclk1n_i[4]]
set_property PACKAGE_PIN AY13 [get_ports gty_refclk0p_i[5]]
set_property PACKAGE_PIN AY12 [get_ports gty_refclk0n_i[5]]
set_property PACKAGE_PIN AW11 [get_ports gty_refclk1p_i[5]]
set_property PACKAGE_PIN AW10 [get_ports gty_refclk1n_i[5]]
set_property PACKAGE_PIN AV13 [get_ports gty_refclk0p_i[6]]
set_property PACKAGE_PIN AV12 [get_ports gty_refclk0n_i[6]]
set_property PACKAGE_PIN AU11 [get_ports gty_refclk1p_i[6]]
set_property PACKAGE_PIN AU10 [get_ports gty_refclk1n_i[6]]
set_property PACKAGE_PIN AP13 [get_ports gty_refclk0p_i[7]]
set_property PACKAGE_PIN AP12 [get_ports gty_refclk0n_i[7]]
set_property PACKAGE_PIN AN11 [get_ports gty_refclk1p_i[7]]
set_property PACKAGE_PIN AN10 [get_ports gty_refclk1n_i[7]]
set_property PACKAGE_PIN AM13 [get_ports gty_refclk0p_i[8]]
set_property PACKAGE_PIN AM12 [get_ports gty_refclk0n_i[8]]
set_property PACKAGE_PIN AL11 [get_ports gty_refclk1p_i[8]]
set_property PACKAGE_PIN AL10 [get_ports gty_refclk1n_i[8]]
set_property PACKAGE_PIN AJ11 [get_ports gty_refclk0p_i[9]]
set_property PACKAGE_PIN AJ10 [get_ports gty_refclk0n_i[9]]
set_property PACKAGE_PIN AG11 [get_ports gty_refclk1p_i[9]]
set_property PACKAGE_PIN AG10 [get_ports gty_refclk1n_i[9]]
set_property PACKAGE_PIN R11 [get_ports gty_refclk0p_i[10]]
set_property PACKAGE_PIN R10 [get_ports gty_refclk0n_i[10]]
set_property PACKAGE_PIN P13 [get_ports gty_refclk1p_i[10]]
set_property PACKAGE_PIN P12 [get_ports gty_refclk1n_i[10]]
set_property PACKAGE_PIN N11 [get_ports gty_refclk0p_i[11]]
set_property PACKAGE_PIN N10 [get_ports gty_refclk0n_i[11]]
set_property PACKAGE_PIN M13 [get_ports gty_refclk1p_i[11]]
set_property PACKAGE_PIN M12 [get_ports gty_refclk1n_i[11]]
set_property PACKAGE_PIN L11 [get_ports gty_refclk0p_i[12]]
set_property PACKAGE_PIN L10 [get_ports gty_refclk0n_i[12]]
set_property PACKAGE_PIN K13 [get_ports gty_refclk1p_i[12]]
set_property PACKAGE_PIN K12 [get_ports gty_refclk1n_i[12]]
##
## Refclk constraints
##
create_clock -name gtrefclk0_3 -period 6.207 [get_ports gty_refclk0p_i[0]]
create_clock -name gtrefclk1_3 -period 6.207 [get_ports gty_refclk1p_i[0]]
set_clock_groups -group [get_clocks gtrefclk0_3 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_3 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_5 -period 6.207 [get_ports gty_refclk0p_i[1]]
create_clock -name gtrefclk1_5 -period 6.207 [get_ports gty_refclk1p_i[1]]
set_clock_groups -group [get_clocks gtrefclk0_5 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_5 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_6 -period 6.207 [get_ports gty_refclk0p_i[2]]
create_clock -name gtrefclk1_6 -period 6.207 [get_ports gty_refclk1p_i[2]]
set_clock_groups -group [get_clocks gtrefclk0_6 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_6 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_7 -period 6.207 [get_ports gty_refclk0p_i[3]]
create_clock -name gtrefclk1_7 -period 6.207 [get_ports gty_refclk1p_i[3]]
set_clock_groups -group [get_clocks gtrefclk0_7 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_7 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_16 -period 6.207 [get_ports gty_refclk0p_i[4]]
create_clock -name gtrefclk1_16 -period 6.207 [get_ports gty_refclk1p_i[4]]
set_clock_groups -group [get_clocks gtrefclk0_16 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_16 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_17 -period 6.207 [get_ports gty_refclk0p_i[5]]
create_clock -name gtrefclk1_17 -period 6.207 [get_ports gty_refclk1p_i[5]]
set_clock_groups -group [get_clocks gtrefclk0_17 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_17 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_18 -period 6.207 [get_ports gty_refclk0p_i[6]]
create_clock -name gtrefclk1_18 -period 6.207 [get_ports gty_refclk1p_i[6]]
set_clock_groups -group [get_clocks gtrefclk0_18 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_18 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_20 -period 6.207 [get_ports gty_refclk0p_i[7]]
create_clock -name gtrefclk1_20 -period 6.207 [get_ports gty_refclk1p_i[7]]
set_clock_groups -group [get_clocks gtrefclk0_20 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_20 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_21 -period 6.207 [get_ports gty_refclk0p_i[8]]
create_clock -name gtrefclk1_21 -period 6.207 [get_ports gty_refclk1p_i[8]]
set_clock_groups -group [get_clocks gtrefclk0_21 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_21 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_22 -period 6.207 [get_ports gty_refclk0p_i[9]]
create_clock -name gtrefclk1_22 -period 6.207 [get_ports gty_refclk1p_i[9]]
set_clock_groups -group [get_clocks gtrefclk0_22 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_22 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_27 -period 6.207 [get_ports gty_refclk0p_i[10]]
create_clock -name gtrefclk1_27 -period 6.207 [get_ports gty_refclk1p_i[10]]
set_clock_groups -group [get_clocks gtrefclk0_27 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_27 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_28 -period 6.207 [get_ports gty_refclk0p_i[11]]
create_clock -name gtrefclk1_28 -period 6.207 [get_ports gty_refclk1p_i[11]]
set_clock_groups -group [get_clocks gtrefclk0_28 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_28 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_29 -period 6.207 [get_ports gty_refclk0p_i[12]]
create_clock -name gtrefclk1_29 -period 6.207 [get_ports gty_refclk1p_i[12]]
set_clock_groups -group [get_clocks gtrefclk0_29 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_29 -include_generated_clocks] -asynchronous
