#!/bin/bash
###############################################################################
#
# Copyright (C) 2014
# ASTRON (Netherlands Institute for Radio Astronomy) <http://www.astron.nl/>
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################

# Purpose: Map command line argument to a tool version
# Description:
#   By using command line arguments like "unb1" or "unb2" to select the tool
#   version it is easier to manage combinations of tool versions.

# General tool and project settings
# - use '. <script>.sh' to have the settings apply in this shell, otherwise they get lost when <script>.sh returns

# Select target
TOOLSET=${1:-}
echo "Make Vivado settings for RadioHDL with :"
echo "  - Tool setting: ${TOOLSET}"
echo "  - Site setting: ${SITE-}"

# Select tool version

if [ "${TOOLSET}" = "vcu108" ]; then
  . ${RADIOHDL}/tools/vivado/vivado_version.sh 2016.2
elif [ "${TOOLSET}" = "vcu110" ]; then
  . ${RADIOHDL}/tools/vivado/vivado_version.sh 2016.2
elif [ "${TOOLSET}" = "gmi" ]; then
#  . ${RADIOHDL}/tools/vivado/vivado_version.sh 2017.2
  . ${RADIOHDL}/tools/vivado/vivado_version.sh 2016.4
elif [ "${TOOLSET}" = "lru" ]; then
  if [ "${SITE-}" = "ASTRON" ]; then
#    . ${RADIOHDL}/tools/vivado/vivado_version.sh 2017.4
    . ${RADIOHDL}/tools/vivado/vivado_version.sh 2019.1
  else
    . ${RADIOHDL}/tools/vivado/vivado_version_csiro.sh 2017.2
  fi
elif [ "${TOOLSET}" = "lru_es" ]; then
  if [ "${SITE-}" = "ASTRON" ]; then
    . ${RADIOHDL}/tools/vivado/vivado_version.sh 2017.4
#    . ${RADIOHDL}/tools/vivado/vivado_version.sh 2019.1
  else
    . ${RADIOHDL}/tools/vivado/vivado_version_csiro.sh 2017.2
  fi
elif [ "${TOOLSET}" = "xh_lru_es" ]; then
  if [ "${SITE-}" = "ASTRON" ]; then
    . ${RADIOHDL}/tools/vivado/vivado_version.sh 2019.1
  else
    . ${RADIOHDL}/tools/vivado/vivado_version_csiro.sh 2019.1
  fi
elif [ "${TOOLSET}" = "kc705" ]; then
  . ${RADIOHDL}/tools/vivado/vivado_version.sh 2018.2
elif [ "${TOOLSET}" = "kcu105" ]; then
  . ${RADIOHDL}/tools/vivado/vivado_version_csiro.sh 2017.2
elif [ "${TOOLSET}" = "kcu116" ]; then
  . ${RADIOHDL}/tools/vivado/vivado_version_csiro.sh 2017.2
#elif [ "${TOOLSET}" = "unb2a" ]; then
#  . ${RADIOHDL}/tools/quartus/quartus_version.sh 15.1
else
  echo "error: unknown tool setting: ${TOOLSET} (choose 'vcu108', 'vcu110', 'gmi', 'lru', 'lru_es', 'kcu116', 'kcu105', 'xh_lru_es')"
  exit 1
fi

# Tool settings
. ${RADIOHDL}/tools/vivado/vivado_generic.sh
