# TCL File Generated by Component Editor 10.0
# Wed Apr 20 10:35:12 CEST 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | avs_common_mm_readlatency0 "avs_common_mm_readlatency0" v1.0
# | ASTRON 2011.04.20.10:35:12
# | MM slave port to conduit with waitrequest, so read latency 0
# | 
# | D:/svnroot/UniBoard_FP7/UniBoard/trunk/Firmware/modules/common/src/vhdl/avs_common_mm_readlatency0.vhd
# | 
# |    ./avs_common_mm_readlatency0.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.0
# | 
package require -exact sopc 10.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module avs_common_mm_readlatency0
# | 
set_module_property DESCRIPTION "MM slave port to conduit with waitrequest, so read latency 0"
set_module_property NAME avs_common_mm_readlatency0
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP Uniboard
set_module_property AUTHOR ASTRON
set_module_property DISPLAY_NAME avs_common_mm_readlatency0
set_module_property TOP_LEVEL_HDL_FILE avs_common_mm_readlatency0.vhd
set_module_property TOP_LEVEL_HDL_MODULE avs_common_mm_readlatency0
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file avs_common_mm_readlatency0.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter g_adr_w NATURAL 5
set_parameter_property g_adr_w DEFAULT_VALUE 5
set_parameter_property g_adr_w DISPLAY_NAME g_adr_w
set_parameter_property g_adr_w TYPE NATURAL
set_parameter_property g_adr_w UNITS None
set_parameter_property g_adr_w AFFECTS_GENERATION false
set_parameter_property g_adr_w HDL_PARAMETER true
add_parameter g_dat_w NATURAL 32
set_parameter_property g_dat_w DEFAULT_VALUE 32
set_parameter_property g_dat_w DISPLAY_NAME g_dat_w
set_parameter_property g_dat_w TYPE NATURAL
set_parameter_property g_dat_w UNITS None
set_parameter_property g_dat_w AFFECTS_GENERATION false
set_parameter_property g_dat_w HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point system
# | 
add_interface system clock end

set_interface_property system ENABLED true

add_interface_port system csi_system_reset reset Input 1
add_interface_port system csi_system_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point mem
# | 
add_interface mem avalon end
set_interface_property mem addressAlignment DYNAMIC
set_interface_property mem associatedClock system
set_interface_property mem burstOnBurstBoundariesOnly false
set_interface_property mem explicitAddressSpan 0
set_interface_property mem holdTime 0
set_interface_property mem isMemoryDevice false
set_interface_property mem isNonVolatileStorage false
set_interface_property mem linewrapBursts false
set_interface_property mem maximumPendingReadTransactions 0
set_interface_property mem printableDevice false
set_interface_property mem readLatency 0
set_interface_property mem readWaitTime 1
set_interface_property mem setupTime 0
set_interface_property mem timingUnits Cycles
set_interface_property mem writeWaitTime 0

set_interface_property mem ASSOCIATED_CLOCK system
set_interface_property mem ENABLED true

add_interface_port mem avs_mem_address address Input g_adr_w
add_interface_port mem avs_mem_write write Input 1
add_interface_port mem avs_mem_writedata writedata Input g_dat_w
add_interface_port mem avs_mem_read read Input 1
add_interface_port mem avs_mem_readdata readdata Output g_dat_w
add_interface_port mem avs_mem_waitrequest waitrequest Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset conduit end

set_interface_property reset ENABLED true

add_interface_port reset coe_reset_export export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clk
# | 
add_interface clk conduit end

set_interface_property clk ENABLED true

add_interface_port clk coe_clk_export export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point address
# | 
add_interface address conduit end

set_interface_property address ENABLED true

add_interface_port address coe_address_export export Output g_adr_w
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point write
# | 
add_interface write conduit end

set_interface_property write ENABLED true

add_interface_port write coe_write_export export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point writedata
# | 
add_interface writedata conduit end

set_interface_property writedata ENABLED true

add_interface_port writedata coe_writedata_export export Output g_dat_w
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point read
# | 
add_interface read conduit end

set_interface_property read ENABLED true

add_interface_port read coe_read_export export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point readdata
# | 
add_interface readdata conduit end

set_interface_property readdata ENABLED true

add_interface_port readdata coe_readdata_export export Input g_dat_w
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point waitrequest
# | 
add_interface waitrequest conduit end

set_interface_property waitrequest ENABLED true

add_interface_port waitrequest coe_waitrequest_export export Input 1
# | 
# +-----------------------------------
