# TCL File Generated by Component Editor 11.1sp2
# Fri Jun 13 11:25:49 CEST 2014
# DO NOT MODIFY


# +-----------------------------------
# | 
# | avs_common_ram_crw_crw "avs_common_ram_crw_crw" v1.0
# | Daniel van der Schuur 2014.06.13.11:25:49
# | Common ram module - Side A = Avalon MM, Side B = conduit
# | 
# | /home/kooistra/svnroot/UniBoard_FP7/UniBoard/trunk/Firmware/modules/common/src/vhdl/avs_common_ram_crw_crw.vhd
# | 
# |    ./avs_common_ram_crw_crw.vhd syn, sim
# |    ./common_mem_pkg.vhd syn, sim
# |    ./common_ram_crw_crw_a_stratix4.vhd syn, sim
# |    ./common_ram_crw_crw.vhd syn, sim
# |    ./common_pipeline.vhd syn, sim
# |    ./common_pkg.vhd syn, sim
# |    /home/kooistra/svnroot/UniBoard_FP7/UniBoard/trunk/Firmware/modules/MegaWizard/mem/ram_crw_crw.vhd syn, sim
# |    /home/kooistra/svnroot/UniBoard_FP7/UniBoard/trunk/Firmware/modules/MegaWizard/mem/ram_cr_cw.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module avs_common_ram_crw_crw
# | 
set_module_property DESCRIPTION "Common ram module - Side A = Avalon MM, Side B = conduit"
set_module_property NAME avs_common_ram_crw_crw
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Uniboard
set_module_property AUTHOR "Daniel van der Schuur"
set_module_property DISPLAY_NAME avs_common_ram_crw_crw
set_module_property TOP_LEVEL_HDL_FILE avs_common_ram_crw_crw.vhd
set_module_property TOP_LEVEL_HDL_MODULE avs_common_ram_crw_crw
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME ""
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file avs_common_ram_crw_crw.vhd {SYNTHESIS SIMULATION}
add_file common_mem_pkg.vhd {SYNTHESIS SIMULATION}
add_file common_ram_crw_crw_a_stratix4.vhd {SYNTHESIS SIMULATION}
add_file common_ram_crw_crw.vhd {SYNTHESIS SIMULATION}
add_file common_pipeline.vhd {SYNTHESIS SIMULATION}
add_file common_pkg.vhd {SYNTHESIS SIMULATION}
add_file /home/kooistra/svnroot/UniBoard_FP7/UniBoard/trunk/Firmware/modules/MegaWizard/mem/ram_crw_crw.vhd {SYNTHESIS SIMULATION}
add_file /home/kooistra/svnroot/UniBoard_FP7/UniBoard/trunk/Firmware/modules/MegaWizard/mem/ram_cr_cw.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter g_latency NATURAL 2
set_parameter_property g_latency DEFAULT_VALUE 2
set_parameter_property g_latency DISPLAY_NAME g_latency
set_parameter_property g_latency TYPE NATURAL
set_parameter_property g_latency UNITS None
set_parameter_property g_latency ALLOWED_RANGES 0:2147483647
set_parameter_property g_latency AFFECTS_GENERATION false
set_parameter_property g_latency HDL_PARAMETER true
add_parameter g_adr_w NATURAL 10
set_parameter_property g_adr_w DEFAULT_VALUE 10
set_parameter_property g_adr_w DISPLAY_NAME g_adr_w
set_parameter_property g_adr_w TYPE NATURAL
set_parameter_property g_adr_w UNITS None
set_parameter_property g_adr_w ALLOWED_RANGES 0:2147483647
set_parameter_property g_adr_w AFFECTS_GENERATION false
set_parameter_property g_adr_w HDL_PARAMETER true
add_parameter g_dat_w NATURAL 9
set_parameter_property g_dat_w DEFAULT_VALUE 9
set_parameter_property g_dat_w DISPLAY_NAME g_dat_w
set_parameter_property g_dat_w TYPE NATURAL
set_parameter_property g_dat_w UNITS None
set_parameter_property g_dat_w ALLOWED_RANGES 0:2147483647
set_parameter_property g_dat_w AFFECTS_GENERATION false
set_parameter_property g_dat_w HDL_PARAMETER true
add_parameter g_nof_dat NATURAL 1024
set_parameter_property g_nof_dat DEFAULT_VALUE 1024
set_parameter_property g_nof_dat DISPLAY_NAME g_nof_dat
set_parameter_property g_nof_dat TYPE NATURAL
set_parameter_property g_nof_dat UNITS None
set_parameter_property g_nof_dat ALLOWED_RANGES 0:2147483647
set_parameter_property g_nof_dat AFFECTS_GENERATION false
set_parameter_property g_nof_dat HDL_PARAMETER true
add_parameter g_init_sl STD_LOGIC 0
set_parameter_property g_init_sl DEFAULT_VALUE 0
set_parameter_property g_init_sl DISPLAY_NAME g_init_sl
set_parameter_property g_init_sl TYPE STD_LOGIC
set_parameter_property g_init_sl UNITS None
set_parameter_property g_init_sl ALLOWED_RANGES 0:1
set_parameter_property g_init_sl AFFECTS_GENERATION false
set_parameter_property g_init_sl HDL_PARAMETER true
add_parameter g_init_file STRING UNUSED
set_parameter_property g_init_file DEFAULT_VALUE UNUSED
set_parameter_property g_init_file DISPLAY_NAME g_init_file
set_parameter_property g_init_file TYPE STRING
set_parameter_property g_init_file UNITS None
set_parameter_property g_init_file AFFECTS_GENERATION false
set_parameter_property g_init_file HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point system
# | 
add_interface system clock end
set_interface_property system clockRate 0

set_interface_property system ENABLED true

add_interface_port system csi_system_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point system_reset
# | 
add_interface system_reset reset end
set_interface_property system_reset associatedClock system
set_interface_property system_reset synchronousEdges DEASSERT

set_interface_property system_reset ENABLED true

add_interface_port system_reset csi_system_reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point ram
# | 
add_interface ram avalon end
set_interface_property ram addressAlignment DYNAMIC
set_interface_property ram addressUnits WORDS
set_interface_property ram associatedClock system
set_interface_property ram associatedReset system_reset
set_interface_property ram burstOnBurstBoundariesOnly false
set_interface_property ram explicitAddressSpan 0
set_interface_property ram holdTime 0
set_interface_property ram isMemoryDevice false
set_interface_property ram isNonVolatileStorage false
set_interface_property ram linewrapBursts false
set_interface_property ram maximumPendingReadTransactions 0
set_interface_property ram printableDevice false
set_interface_property ram readLatency 2
set_interface_property ram readWaitStates 0
set_interface_property ram readWaitTime 0
set_interface_property ram setupTime 0
set_interface_property ram timingUnits Cycles
set_interface_property ram writeWaitTime 0

set_interface_property ram ENABLED true

add_interface_port ram avs_ram_address address Input g_adr_w
add_interface_port ram avs_ram_write write Input 1
add_interface_port ram avs_ram_writedata writedata Input g_dat_w
add_interface_port ram avs_ram_read read Input 1
add_interface_port ram avs_ram_readdata readdata Output g_dat_w
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point rst
# | 
add_interface rst conduit end

set_interface_property rst ENABLED true

add_interface_port rst coe_rst_export export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clk
# | 
add_interface clk conduit end

set_interface_property clk ENABLED true

add_interface_port clk coe_clk_export export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point wr_en
# | 
add_interface wr_en conduit end

set_interface_property wr_en ENABLED true

add_interface_port wr_en coe_wr_en_export export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point wr_dat
# | 
add_interface wr_dat conduit end

set_interface_property wr_dat ENABLED true

add_interface_port wr_dat coe_wr_dat_export export Input g_dat_w
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point adr
# | 
add_interface adr conduit end

set_interface_property adr ENABLED true

add_interface_port adr coe_adr_export export Input g_adr_w
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point rd_en
# | 
add_interface rd_en conduit end

set_interface_property rd_en ENABLED true

add_interface_port rd_en coe_rd_en_export export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point rd_dat
# | 
add_interface rd_dat conduit end

set_interface_property rd_dat ENABLED true

add_interface_port rd_dat coe_rd_dat_export export Output g_dat_w
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point rd_val
# | 
add_interface rd_val conduit end

set_interface_property rd_val ENABLED true

add_interface_port rd_val coe_rd_val_export export Output 1
# | 
# +-----------------------------------
