
# file: ibert_ultrascaleplus_gty_0.xdc
####################################################################################
##   ____  ____ 
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 2012.3
##  \   \         Application : IBERT Ultrascale
##  /   /         Filename : example_ibert_ultrascaleplus_gty_0.xdc
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\
##
##
## 
## Generated by Xilinx IBERT Ultrascale
##**************************************************************************
##
## Icon Constraints
##
create_clock -name D_CLK -period 6.4 [get_ports gty_sysclkp_i]
set_clock_groups -group [get_clocks D_CLK -include_generated_clocks] -asynchronous

set_property C_CLK_INPUT_FREQ_HZ 156250000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER true [get_debug_cores dbg_hub]
##
##Eye scan 
##
set_property ES_EYE_SCAN_EN TRUE [get_cells u_ibert_gty_core/inst/QUAD[*].u_q/CH[*].u_ch/u_gtye4_channel]
##
##gtrefclk lock constraints
##
set_property PACKAGE_PIN W11 [get_ports gty_refclk0p_i[0]]
set_property PACKAGE_PIN W10 [get_ports gty_refclk0n_i[0]]
set_property PACKAGE_PIN V13 [get_ports gty_refclk1p_i[0]]
set_property PACKAGE_PIN V12 [get_ports gty_refclk1n_i[0]]
set_property PACKAGE_PIN U11 [get_ports gty_refclk0p_i[1]]
set_property PACKAGE_PIN U10 [get_ports gty_refclk0n_i[1]]
set_property PACKAGE_PIN T13 [get_ports gty_refclk1p_i[1]]
set_property PACKAGE_PIN T12 [get_ports gty_refclk1n_i[1]]
set_property PACKAGE_PIN R11 [get_ports gty_refclk0p_i[2]]
set_property PACKAGE_PIN R10 [get_ports gty_refclk0n_i[2]]
set_property PACKAGE_PIN P13 [get_ports gty_refclk1p_i[2]]
set_property PACKAGE_PIN P12 [get_ports gty_refclk1n_i[2]]
set_property PACKAGE_PIN N11 [get_ports gty_refclk0p_i[3]]
set_property PACKAGE_PIN N10 [get_ports gty_refclk0n_i[3]]
set_property PACKAGE_PIN M13 [get_ports gty_refclk1p_i[3]]
set_property PACKAGE_PIN M12 [get_ports gty_refclk1n_i[3]]
##
## Refclk constraints
##
create_clock -name gtrefclk0_25 -period 5.334 [get_ports gty_refclk0p_i[0]]
create_clock -name gtrefclk1_25 -period 5.334 [get_ports gty_refclk1p_i[0]]
set_clock_groups -group [get_clocks gtrefclk0_25 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_25 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_26 -period 5.334 [get_ports gty_refclk0p_i[1]]
create_clock -name gtrefclk1_26 -period 5.334 [get_ports gty_refclk1p_i[1]]
set_clock_groups -group [get_clocks gtrefclk0_26 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_26 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_27 -period 5.334 [get_ports gty_refclk0p_i[2]]
create_clock -name gtrefclk1_27 -period 5.334 [get_ports gty_refclk1p_i[2]]
set_clock_groups -group [get_clocks gtrefclk0_27 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_27 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_28 -period 5.334 [get_ports gty_refclk0p_i[3]]
create_clock -name gtrefclk1_28 -period 5.334 [get_ports gty_refclk1p_i[3]]
set_clock_groups -group [get_clocks gtrefclk0_28 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_28 -include_generated_clocks] -asynchronous
##
## System clock pin locs and timing constraints
##
set_property PACKAGE_PIN BE22 [get_ports gty_sysclkp_i]
set_property IOSTANDARD LVDS [get_ports gty_sysclkp_i]
##
## TX/RX out clock clock constraints
##
# GT X0Y40
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[0].u_q/CH[0].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[0].u_q/CH[0].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y41
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[0].u_q/CH[1].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[0].u_q/CH[1].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y42
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[0].u_q/CH[2].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[0].u_q/CH[2].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y43
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[0].u_q/CH[3].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[0].u_q/CH[3].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y44
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[1].u_q/CH[0].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[1].u_q/CH[0].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y45
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[1].u_q/CH[1].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[1].u_q/CH[1].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y46
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[1].u_q/CH[2].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[1].u_q/CH[2].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y47
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[1].u_q/CH[3].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[1].u_q/CH[3].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y48
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[2].u_q/CH[0].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[2].u_q/CH[0].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y49
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[2].u_q/CH[1].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[2].u_q/CH[1].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y50
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[2].u_q/CH[2].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[2].u_q/CH[2].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y51
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[2].u_q/CH[3].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[2].u_q/CH[3].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y52
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[3].u_q/CH[0].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[3].u_q/CH[0].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y53
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[3].u_q/CH[1].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[3].u_q/CH[1].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y54
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[3].u_q/CH[2].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[3].u_q/CH[2].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y55
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[3].u_q/CH[3].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[3].u_q/CH[3].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]

# imported and changed from system.xdc (XTP374 HMC GTH ibert application note for VCU110)
# # Gemini HMC_C:
# #
# #set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 8 [current_design]
# #set_property BITSTREAM.CONFIG.EXTMASTERCCLK_EN div-1 [current_design]
# #set_property BITSTREAM.CONFIG.SPI_FALL_EDGE YES [current_design ]
# #set_property BITSTREAM.config.SPI_opcode 0x6B [current_design ]
# #set_property CONFIG_MODE SPIx8 [current_design]
# #set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
# #set_property BITSTREAM.CONFIG.UNUSEDPIN Pullup [current_design]
# #set_property CFGBVS GND [current_design]
# #set_property CONFIG_VOLTAGE 1.8 [current_design]
#
# # Gemini hardwired:
# #set_property PACKAGE_PIN AW28 [get_ports iic_mux_reset_b[2]]
# #set_property IOSTANDARD LVCMOS15 [get_ports iic_mux_reset_b[2]]
#
# # Gemini hardwired:
# #set_property PACKAGE_PIN AR18 [get_ports iic_mux_reset_b[1]]
# #set_property IOSTANDARD LVCMOS18 [get_ports iic_mux_reset_b[1]]
#
# # Gemini hardwired:
# #set_property PACKAGE_PIN AW21 [get_ports iic_mux_reset_b[0]]
# #set_property IOSTANDARD LVCMOS18 [get_ports iic_mux_reset_b[0]]
#
# # Gemini hardwired:
# #set_property PACKAGE_PIN AV30 [get_ports hmc_refclk_sel_tri_o[0]]
# #set_property IOSTANDARD LVCMOS15 [get_ports hmc_refclk_sel_tri_o[0]]
#
# # Gemini hardwired:
# #set_property PACKAGE_PIN BB27 [get_ports lxrxps_tri_o[1]]
# #set_property IOSTANDARD LVCMOS15 [get_ports lxrxps_tri_o[1]]
#
# # Gemini hardwired:
# #set_property PACKAGE_PIN AY30 [get_ports lxrxps_tri_o[0]]
# #set_property IOSTANDARD LVCMOS15 [get_ports lxrxps_tri_o[0]]
#
# # Gemini hardwired:
# #set_property PACKAGE_PIN AY29 [get_ports lxtxps_tri_i[1]]
# #set_property IOSTANDARD LVCMOS15 [get_ports lxtxps_tri_i[1]]
#
# # Gemini hardwired:
# #set_property PACKAGE_PIN AW27 [get_ports lxtxps_tri_i[0]]
# #set_property IOSTANDARD LVCMOS15 [get_ports lxtxps_tri_i[0]]
#
# # Gemini hardwired:
# #set_property PACKAGE_PIN BB26 [get_ports refclk_boot_tri_o[1]]
# #set_property IOSTANDARD LVCMOS15 [get_ports refclk_boot_tri_o[1]]
#

# Gemini hardwired:
# #set_property PACKAGE_PIN BA26 [get_ports refclk_boot_tri_o[0]]
# #set_property IOSTANDARD LVCMOS15 [get_ports refclk_boot_tri_o[0]]

set_property PACKAGE_PIN J15 [get_ports ferr_n_tri_i[0]]
set_property IOSTANDARD LVCMOS15 [get_ports ferr_n_tri_i[0]]

set_property PACKAGE_PIN J16 [get_ports iic_main_scl_io]
set_property IOSTANDARD LVCMOS15 [get_ports iic_main_scl_io]

set_property PACKAGE_PIN J19 [get_ports iic_main_sda_io]
set_property IOSTANDARD LVCMOS15 [get_ports iic_main_sda_io]

# Gemini debug[0]
set_property PACKAGE_PIN A27 [get_ports rs232_uart_rxd]
set_property IOSTANDARD LVCMOS18 [get_ports rs232_uart_rxd]

# Gemini debug[1]
set_property PACKAGE_PIN B27 [get_ports rs232_uart_txd]
set_property IOSTANDARD LVCMOS18 [get_ports rs232_uart_txd]

# Gemini debug[2]
set_property PACKAGE_PIN B25 [get_ports reset]
set_property IOSTANDARD LVCMOS18 [get_ports reset]

