
# file: ibert_ultrascaleplus_gty_0.xdc
####################################################################################
##   ____  ____ 
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 2012.3
##  \   \         Application : IBERT Ultrascale
##  /   /         Filename : example_ibert_ultrascaleplus_gty_0.xdc
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\
##
##
## 
## Generated by Xilinx IBERT Ultrascale
##**************************************************************************
##
## Icon Constraints
##
create_clock -name D_CLK -period 6.4 [get_ports gty_sysclkp_i]
set_clock_groups -group [get_clocks D_CLK -include_generated_clocks] -asynchronous

set_property C_CLK_INPUT_FREQ_HZ 156250000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER true [get_debug_cores dbg_hub]
##
##Eye scan 
##
set_property ES_EYE_SCAN_EN TRUE [get_cells u_ibert_gty_core/inst/QUAD[*].u_q/CH[*].u_ch/u_gtye4_channel]
##
##gtrefclk lock constraints
##
set_property PACKAGE_PIN AM13 [get_ports gty_refclk0p_i[0]]
set_property PACKAGE_PIN AM12 [get_ports gty_refclk0n_i[0]]
set_property PACKAGE_PIN AL11 [get_ports gty_refclk1p_i[0]]
set_property PACKAGE_PIN AL10 [get_ports gty_refclk1n_i[0]]
set_property PACKAGE_PIN AJ11 [get_ports gty_refclk0p_i[1]]
set_property PACKAGE_PIN AJ10 [get_ports gty_refclk0n_i[1]]
set_property PACKAGE_PIN AG11 [get_ports gty_refclk1p_i[1]]
set_property PACKAGE_PIN AG10 [get_ports gty_refclk1n_i[1]]
set_property PACKAGE_PIN AE11 [get_ports gty_refclk0p_i[2]]
set_property PACKAGE_PIN AE10 [get_ports gty_refclk0n_i[2]]
set_property PACKAGE_PIN AC11 [get_ports gty_refclk1p_i[2]]
set_property PACKAGE_PIN AC10 [get_ports gty_refclk1n_i[2]]
set_property PACKAGE_PIN AA11 [get_ports gty_refclk0p_i[3]]
set_property PACKAGE_PIN AA10 [get_ports gty_refclk0n_i[3]]
set_property PACKAGE_PIN Y13 [get_ports gty_refclk1p_i[3]]
set_property PACKAGE_PIN Y12 [get_ports gty_refclk1n_i[3]]
##
## Refclk constraints
##
create_clock -name gtrefclk0_21 -period 5.334 [get_ports gty_refclk0p_i[0]]
create_clock -name gtrefclk1_21 -period 5.334 [get_ports gty_refclk1p_i[0]]
set_clock_groups -group [get_clocks gtrefclk0_21 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_21 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_22 -period 5.334 [get_ports gty_refclk0p_i[1]]
create_clock -name gtrefclk1_22 -period 5.334 [get_ports gty_refclk1p_i[1]]
set_clock_groups -group [get_clocks gtrefclk0_22 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_22 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_23 -period 5.334 [get_ports gty_refclk0p_i[2]]
create_clock -name gtrefclk1_23 -period 5.334 [get_ports gty_refclk1p_i[2]]
set_clock_groups -group [get_clocks gtrefclk0_23 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_23 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_24 -period 5.334 [get_ports gty_refclk0p_i[3]]
create_clock -name gtrefclk1_24 -period 5.334 [get_ports gty_refclk1p_i[3]]
set_clock_groups -group [get_clocks gtrefclk0_24 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_24 -include_generated_clocks] -asynchronous
##
## System clock pin locs and timing constraints
##
set_property PACKAGE_PIN BE22 [get_ports gty_sysclkp_i]
set_property IOSTANDARD LVDS [get_ports gty_sysclkp_i]
##
## TX/RX out clock clock constraints
##
# GT X0Y24
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[0].u_q/CH[0].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[0].u_q/CH[0].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y25
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[0].u_q/CH[1].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[0].u_q/CH[1].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y26
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[0].u_q/CH[2].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[0].u_q/CH[2].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y27
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[0].u_q/CH[3].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[0].u_q/CH[3].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y28
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[1].u_q/CH[0].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[1].u_q/CH[0].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y29
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[1].u_q/CH[1].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[1].u_q/CH[1].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y30
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[1].u_q/CH[2].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[1].u_q/CH[2].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y31
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[1].u_q/CH[3].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[1].u_q/CH[3].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y32
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[2].u_q/CH[0].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[2].u_q/CH[0].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y33
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[2].u_q/CH[1].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[2].u_q/CH[1].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y34
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[2].u_q/CH[2].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[2].u_q/CH[2].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y35
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[2].u_q/CH[3].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[2].u_q/CH[3].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y36
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[3].u_q/CH[0].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[3].u_q/CH[0].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y37
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[3].u_q/CH[1].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[3].u_q/CH[1].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y38
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[3].u_q/CH[2].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[3].u_q/CH[2].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]
# GT X0Y39
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[3].u_q/CH[3].u_ch/u_gtye4_channel/RXOUTCLK}] -include_generated_clocks]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {u_ibert_gty_core/inst/QUAD[3].u_q/CH[3].u_ch/u_gtye4_channel/TXOUTCLK}] -include_generated_clocks]

# imported and changed from system.xdc (XTP374 HMC GTH ibert application note for VCU110)
# # Gemini HMC_D:
# #
# #set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 8 [current_design]
# #set_property BITSTREAM.CONFIG.EXTMASTERCCLK_EN div-1 [current_design]
# #set_property BITSTREAM.CONFIG.SPI_FALL_EDGE YES [current_design ]
# #set_property BITSTREAM.config.SPI_opcode 0x6B [current_design ]
# #set_property CONFIG_MODE SPIx8 [current_design]
# #set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
# #set_property BITSTREAM.CONFIG.UNUSEDPIN Pullup [current_design]
# #set_property CFGBVS GND [current_design]
# #set_property CONFIG_VOLTAGE 1.8 [current_design]
#
# # Gemini hardwired:
# #set_property PACKAGE_PIN AW28 [get_ports iic_mux_reset_b[2]]
# #set_property IOSTANDARD LVCMOS15 [get_ports iic_mux_reset_b[2]]
#
# # Gemini hardwired:
# #set_property PACKAGE_PIN AR18 [get_ports iic_mux_reset_b[1]]
# #set_property IOSTANDARD LVCMOS18 [get_ports iic_mux_reset_b[1]]
#
# # Gemini hardwired:
# #set_property PACKAGE_PIN AW21 [get_ports iic_mux_reset_b[0]]
# #set_property IOSTANDARD LVCMOS18 [get_ports iic_mux_reset_b[0]]
#
# # Gemini hardwired:
# #set_property PACKAGE_PIN AV30 [get_ports hmc_refclk_sel_tri_o[0]]
# #set_property IOSTANDARD LVCMOS15 [get_ports hmc_refclk_sel_tri_o[0]]
#
# # Gemini hardwired:
# #set_property PACKAGE_PIN BB27 [get_ports lxrxps_tri_o[1]]
# #set_property IOSTANDARD LVCMOS15 [get_ports lxrxps_tri_o[1]]
#
# # Gemini hardwired:
# #set_property PACKAGE_PIN AY30 [get_ports lxrxps_tri_o[0]]
# #set_property IOSTANDARD LVCMOS15 [get_ports lxrxps_tri_o[0]]
#
# # Gemini hardwired:
# #set_property PACKAGE_PIN AY29 [get_ports lxtxps_tri_i[1]]
# #set_property IOSTANDARD LVCMOS15 [get_ports lxtxps_tri_i[1]]
#
# # Gemini hardwired:
# #set_property PACKAGE_PIN AW27 [get_ports lxtxps_tri_i[0]]
# #set_property IOSTANDARD LVCMOS15 [get_ports lxtxps_tri_i[0]]
#
# # Gemini hardwired:
# #set_property PACKAGE_PIN BB26 [get_ports refclk_boot_tri_o[1]]
# #set_property IOSTANDARD LVCMOS15 [get_ports refclk_boot_tri_o[1]]
#
# # Gemini hardwired:
# #set_property PACKAGE_PIN BA26 [get_ports refclk_boot_tri_o[0]]
# #set_property IOSTANDARD LVCMOS15 [get_ports refclk_boot_tri_o[0]]

set_property PACKAGE_PIN P15 [get_ports ferr_n_tri_i[0]]
set_property IOSTANDARD LVCMOS15 [get_ports ferr_n_tri_i[0]]

set_property PACKAGE_PIN U15 [get_ports iic_main_scl_io]
set_property IOSTANDARD LVCMOS15 [get_ports iic_main_scl_io]

set_property PACKAGE_PIN T15 [get_ports iic_main_sda_io]
set_property IOSTANDARD LVCMOS15 [get_ports iic_main_sda_io]

# Gemini debug[0]
set_property PACKAGE_PIN A27 [get_ports rs232_uart_rxd]
set_property IOSTANDARD LVCMOS18 [get_ports rs232_uart_rxd]

# Gemini debug[1]
set_property PACKAGE_PIN B27 [get_ports rs232_uart_txd]
set_property IOSTANDARD LVCMOS18 [get_ports rs232_uart_txd]

# Gemini debug[2]
set_property PACKAGE_PIN B25 [get_ports reset]
set_property IOSTANDARD LVCMOS18 [get_ports reset]

