set_property PACKAGE_PIN BK25 [get_ports aux_in_alert]
set_property PACKAGE_PIN BJ30 [get_ports aux_in_scl]
set_property PACKAGE_PIN BK23 [get_ports aux_in_sda]
set_property PACKAGE_PIN D23 [get_ports aux_out_alert]
set_property PACKAGE_PIN G22 [get_ports aux_out_scl]
set_property PACKAGE_PIN H22 [get_ports aux_out_sda]
set_property PACKAGE_PIN E23 [get_ports aux_pgood]
set_property PACKAGE_PIN J23 [get_ports aux_pwr_off]
set_property IOSTANDARD LVCMOS18 [get_ports aux_in_alert]
set_property IOSTANDARD LVCMOS18 [get_ports aux_in_scl]
set_property IOSTANDARD LVCMOS18 [get_ports aux_in_sda]
set_property IOSTANDARD LVCMOS18 [get_ports aux_out_alert]
set_property IOSTANDARD LVCMOS18 [get_ports aux_out_scl]
set_property IOSTANDARD LVCMOS18 [get_ports aux_out_sda]
set_property IOSTANDARD LVCMOS18 [get_ports aux_pgood]
set_property IOSTANDARD LVCMOS18 [get_ports aux_pwr_off]


# See http://www.xilinx.com/support/documentation/sw_manuals/xilinx2016_1/ug912-vivado-properties.pdf
# page 176:

# This is an output, no termination:
set_property -dict {PACKAGE_PIN B26 IOSTANDARD LVDS} [get_ports aux_sfp_tx_n]
set_property -dict {PACKAGE_PIN C26 IOSTANDARD LVDS} [get_ports aux_sfp_tx_p]

set_property PACKAGE_PIN C27 [get_ports aux_sfp_tx_sel]
set_property IOSTANDARD LVCMOS18 [get_ports aux_sfp_tx_sel]


set_property -dict {PACKAGE_PIN BE22 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports clk_b_p]
set_property -dict {PACKAGE_PIN BF22 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports clk_b_n]
#set_property -dict {PACKAGE_PIN BE22 IOSTANDARD LVDS } [get_ports clk_b_p]
#set_property -dict {PACKAGE_PIN BF22 IOSTANDARD LVDS } [get_ports clk_b_n]

set_property -dict {PACKAGE_PIN A28 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports clk_e_p]
set_property -dict {PACKAGE_PIN A29 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports clk_e_n]
#set_property -dict {PACKAGE_PIN A28 IOSTANDARD LVDS } [get_ports clk_e_p]
#set_property -dict {PACKAGE_PIN A29 IOSTANDARD LVDS } [get_ports clk_e_n]

set_property PACKAGE_PIN C29 [get_ports clk_f]
set_property IOSTANDARD LVCMOS18 [get_ports clk_f]


set_property -dict {PACKAGE_PIN K28 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports clk_mmbx_n]
set_property -dict {PACKAGE_PIN K27 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports clk_mmbx_p]
#set_property -dict {PACKAGE_PIN K28 IOSTANDARD LVDS } [get_ports clk_mmbx_n]
#set_property -dict {PACKAGE_PIN K27 IOSTANDARD LVDS } [get_ports clk_mmbx_p]


set_property -dict {PACKAGE_PIN L29 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports clk_sfp_n]
set_property -dict {PACKAGE_PIN L28 IOSTANDARD LVDS DIFF_TERM_ADV TERM_100} [get_ports clk_sfp_p]
#set_property -dict {PACKAGE_PIN L29 IOSTANDARD LVDS } [get_ports clk_sfp_n]
#set_property -dict {PACKAGE_PIN L28 IOSTANDARD LVDS } [get_ports clk_sfp_p]


set_property PACKAGE_PIN A27 [get_ports {debug[0]}]
set_property PACKAGE_PIN B27 [get_ports {debug[1]}]
set_property PACKAGE_PIN B25 [get_ports {debug[2]}]
set_property PACKAGE_PIN A25 [get_ports {debug[3]}]
set_property PACKAGE_PIN A24 [get_ports debug_mmbx]
set_property IOSTANDARD LVCMOS18 [get_ports {debug[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {debug[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {debug[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {debug[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports debug_mmbx]

set_property PACKAGE_PIN AE42 [get_ports hmc_a_clk_n]
set_property PACKAGE_PIN AE41 [get_ports hmc_a_clk_p]

set_property PACKAGE_PIN K37 [get_ports hmc_a_ferr_n]
set_property IOSTANDARD LVCMOS15 [get_ports hmc_a_ferr_n]
set_property PULLUP true [get_ports hmc_a_ferr_n]

set_property PACKAGE_PIN L37 [get_ports hmc_a_p_rst_n]
set_property IOSTANDARD LVCMOS15 [get_ports hmc_a_p_rst_n]





# set_property PACKAGE_PIN AF49 [get_ports {hmc_a_rx_n[0]}] 
# set_property PACKAGE_PIN AL51 [get_ports {hmc_a_rx_n[1]}] 
# set_property PACKAGE_PIN AH49 [get_ports {hmc_a_rx_n[2]}] 
# set_property PACKAGE_PIN AK49 [get_ports {hmc_a_rx_n[3]}] 
# set_property PACKAGE_PIN AG51 [get_ports {hmc_a_rx_n[4]}] 
# set_property PACKAGE_PIN AJ51 [get_ports {hmc_a_rx_n[5]}] 
# set_property PACKAGE_PIN AN51 [get_ports {hmc_a_rx_n[6]}] 
# set_property PACKAGE_PIN AM49 [get_ports {hmc_a_rx_n[7]}] 
# set_property PACKAGE_PIN V49 [get_ports {hmc_a_rx_n[8]}]  
# set_property PACKAGE_PIN Y49 [get_ports {hmc_a_rx_n[9]}]  
# set_property PACKAGE_PIN AB49 [get_ports {hmc_a_rx_n[10]}]
# set_property PACKAGE_PIN AD49 [get_ports {hmc_a_rx_n[11]}]
# set_property PACKAGE_PIN W51 [get_ports {hmc_a_rx_n[12]}] 
# set_property PACKAGE_PIN AA51 [get_ports {hmc_a_rx_n[13]}]
# set_property PACKAGE_PIN AC51 [get_ports {hmc_a_rx_n[14]}]
# set_property PACKAGE_PIN AE51 [get_ports {hmc_a_rx_n[15]}]
# set_property PACKAGE_PIN AF48 [get_ports {hmc_a_rx_p[0]}]
# set_property PACKAGE_PIN AL50 [get_ports {hmc_a_rx_p[1]}]
# set_property PACKAGE_PIN AH48 [get_ports {hmc_a_rx_p[2]}]
# set_property PACKAGE_PIN AG50 [get_ports {hmc_a_rx_p[4]}]
# set_property PACKAGE_PIN AJ50 [get_ports {hmc_a_rx_p[5]}]
# set_property PACKAGE_PIN AN50 [get_ports {hmc_a_rx_p[6]}]
# set_property PACKAGE_PIN AM48 [get_ports {hmc_a_rx_p[7]}]
# set_property PACKAGE_PIN V48 [get_ports {hmc_a_rx_p[8]}]
# set_property PACKAGE_PIN Y48 [get_ports {hmc_a_rx_p[9]}]
# set_property PACKAGE_PIN AB48 [get_ports {hmc_a_rx_p[10]}]
# set_property PACKAGE_PIN AD48 [get_ports {hmc_a_rx_p[11]}]
# set_property PACKAGE_PIN W50 [get_ports {hmc_a_rx_p[12]}]
# set_property PACKAGE_PIN AA50 [get_ports {hmc_a_rx_p[13]}]
# set_property PACKAGE_PIN AC50 [get_ports {hmc_a_rx_p[14]}]
# set_property PACKAGE_PIN AE50 [get_ports {hmc_a_rx_p[15]}]



set_property IOSTANDARD LVCMOS15 [get_ports hmc_a_scl]
set_property PACKAGE_PIN M37 [get_ports hmc_a_scl]
set_property IOSTANDARD LVCMOS15 [get_ports hmc_a_sda]
set_property PACKAGE_PIN N37 [get_ports hmc_a_sda]



# set_property PACKAGE_PIN AF44 [get_ports {hmc_a_tx_n[0]}]
# set_property PACKAGE_PIN AL46 [get_ports {hmc_a_tx_n[1]}]
# set_property PACKAGE_PIN AH44 [get_ports {hmc_a_tx_n[2]}]
# set_property PACKAGE_PIN AK44 [get_ports {hmc_a_tx_n[3]}]
# set_property PACKAGE_PIN AG46 [get_ports {hmc_a_tx_n[4]}]
# set_property PACKAGE_PIN AJ46 [get_ports {hmc_a_tx_n[5]}]
# set_property PACKAGE_PIN AN46 [get_ports {hmc_a_tx_n[6]}]
# set_property PACKAGE_PIN AM44 [get_ports {hmc_a_tx_n[7]}]
# set_property PACKAGE_PIN V44 [get_ports {hmc_a_tx_n[8]}]
# set_property PACKAGE_PIN Y44 [get_ports {hmc_a_tx_n[9]}]
# set_property PACKAGE_PIN AB44 [get_ports {hmc_a_tx_n[10]}]
# set_property PACKAGE_PIN AD44 [get_ports {hmc_a_tx_n[11]}]
# set_property PACKAGE_PIN W46 [get_ports {hmc_a_tx_n[12]}]
# set_property PACKAGE_PIN AA46 [get_ports {hmc_a_tx_n[13]}]
# set_property PACKAGE_PIN AC46 [get_ports {hmc_a_tx_n[14]}]
# set_property PACKAGE_PIN AE46 [get_ports {hmc_a_tx_n[15]}]
# set_property PACKAGE_PIN AF43 [get_ports {hmc_a_tx_p[0]}]
# set_property PACKAGE_PIN AL45 [get_ports {hmc_a_tx_p[1]}]
# set_property PACKAGE_PIN AH43 [get_ports {hmc_a_tx_p[2]}]
# set_property PACKAGE_PIN AK48 [get_ports {hmc_a_rx_p[3]}]
# set_property PACKAGE_PIN AK43 [get_ports {hmc_a_tx_p[3]}]
# set_property PACKAGE_PIN AG45 [get_ports {hmc_a_tx_p[4]}]
# set_property PACKAGE_PIN AJ45 [get_ports {hmc_a_tx_p[5]}]
# set_property PACKAGE_PIN AN45 [get_ports {hmc_a_tx_p[6]}]
# set_property PACKAGE_PIN AM43 [get_ports {hmc_a_tx_p[7]}]
# set_property PACKAGE_PIN V43 [get_ports {hmc_a_tx_p[8]}]
# set_property PACKAGE_PIN Y43 [get_ports {hmc_a_tx_p[9]}]
# set_property PACKAGE_PIN AB43 [get_ports {hmc_a_tx_p[10]}]
# set_property PACKAGE_PIN AD43 [get_ports {hmc_a_tx_p[11]}]
# set_property PACKAGE_PIN W45 [get_ports {hmc_a_tx_p[12]}]
# set_property PACKAGE_PIN AA45 [get_ports {hmc_a_tx_p[13]}]
# set_property PACKAGE_PIN AC45 [get_ports {hmc_a_tx_p[14]}]
# set_property PACKAGE_PIN AE45 [get_ports {hmc_a_tx_p[15]}]



set_property PACKAGE_PIN U42 [get_ports hmc_b_clk_n]
set_property PACKAGE_PIN U41 [get_ports hmc_b_clk_p]

set_property IOSTANDARD LVCMOS15 [get_ports hmc_b_ferr_n]
set_property PACKAGE_PIN J34 [get_ports hmc_b_ferr_n]
set_property PULLUP true [get_ports hmc_b_ferr_n]

set_property IOSTANDARD LVCMOS15 [get_ports hmc_b_p_rst_n]
set_property PACKAGE_PIN J33 [get_ports hmc_b_p_rst_n]



# set_property PACKAGE_PIN L51 [get_ports {hmc_b_rx_n[0]}]
# set_property PACKAGE_PIN P49 [get_ports {hmc_b_rx_n[1]}]
# set_property PACKAGE_PIN N51 [get_ports {hmc_b_rx_n[2]}]
# set_property PACKAGE_PIN U51 [get_ports {hmc_b_rx_n[3]}]
# set_property PACKAGE_PIN K49 [get_ports {hmc_b_rx_n[4]}]
# set_property PACKAGE_PIN T49 [get_ports {hmc_b_rx_n[6]}]
# set_property PACKAGE_PIN R51 [get_ports {hmc_b_rx_n[7]}]
# set_property PACKAGE_PIN D49 [get_ports {hmc_b_rx_n[8]}]
# set_property PACKAGE_PIN C47 [get_ports {hmc_b_rx_n[9]}]
# set_property PACKAGE_PIN J51 [get_ports {hmc_b_rx_n[11]}]
# set_property PACKAGE_PIN E47 [get_ports {hmc_b_rx_n[12]}]
# set_property PACKAGE_PIN E51 [get_ports {hmc_b_rx_n[13]}]
# set_property PACKAGE_PIN F49 [get_ports {hmc_b_rx_n[14]}]
# set_property PACKAGE_PIN H49 [get_ports {hmc_b_rx_n[15]}]
# set_property PACKAGE_PIN L50 [get_ports {hmc_b_rx_p[0]}]
# set_property PACKAGE_PIN P48 [get_ports {hmc_b_rx_p[1]}]
# set_property PACKAGE_PIN N50 [get_ports {hmc_b_rx_p[2]}]
# set_property PACKAGE_PIN U50 [get_ports {hmc_b_rx_p[3]}]
# set_property PACKAGE_PIN K48 [get_ports {hmc_b_rx_p[4]}]
# set_property PACKAGE_PIN T48 [get_ports {hmc_b_rx_p[6]}]
# set_property PACKAGE_PIN R50 [get_ports {hmc_b_rx_p[7]}]
# set_property PACKAGE_PIN D48 [get_ports {hmc_b_rx_p[8]}]
# set_property PACKAGE_PIN C46 [get_ports {hmc_b_rx_p[9]}]
# set_property PACKAGE_PIN J50 [get_ports {hmc_b_rx_p[11]}]
# set_property PACKAGE_PIN E46 [get_ports {hmc_b_rx_p[12]}]
# set_property PACKAGE_PIN E50 [get_ports {hmc_b_rx_p[13]}]
# set_property PACKAGE_PIN F48 [get_ports {hmc_b_rx_p[14]}]
# set_property PACKAGE_PIN H48 [get_ports {hmc_b_rx_p[15]}]



set_property IOSTANDARD LVCMOS15 [get_ports hmc_b_scl]
set_property PACKAGE_PIN J36 [get_ports hmc_b_scl]
set_property IOSTANDARD LVCMOS15 [get_ports hmc_b_sda]
set_property PACKAGE_PIN J35 [get_ports hmc_b_sda]




# set_property PACKAGE_PIN L46 [get_ports {hmc_b_tx_n[0]}]
# set_property PACKAGE_PIN P44 [get_ports {hmc_b_tx_n[1]}]
# set_property PACKAGE_PIN N46 [get_ports {hmc_b_tx_n[2]}]
# set_property PACKAGE_PIN U46 [get_ports {hmc_b_tx_n[3]}]
# set_property PACKAGE_PIN K44 [get_ports {hmc_b_tx_n[4]}]
# set_property PACKAGE_PIN T44 [get_ports {hmc_b_tx_n[6]}]
# set_property PACKAGE_PIN R46 [get_ports {hmc_b_tx_n[7]}]
# set_property PACKAGE_PIN B44 [get_ports {hmc_b_tx_n[8]}]
# set_property PACKAGE_PIN E42 [get_ports {hmc_b_tx_n[9]}]
# set_property PACKAGE_PIN J46 [get_ports {hmc_b_tx_n[11]}]
# set_property PACKAGE_PIN C42 [get_ports {hmc_b_tx_n[12]}]
# set_property PACKAGE_PIN D44 [get_ports {hmc_b_tx_n[13]}]
# set_property PACKAGE_PIN F44 [get_ports {hmc_b_tx_n[14]}]
# set_property PACKAGE_PIN H44 [get_ports {hmc_b_tx_n[15]}]
# set_property PACKAGE_PIN L45 [get_ports {hmc_b_tx_p[0]}]
# set_property PACKAGE_PIN P43 [get_ports {hmc_b_tx_p[1]}]
# set_property PACKAGE_PIN N45 [get_ports {hmc_b_tx_p[2]}]
# set_property PACKAGE_PIN U45 [get_ports {hmc_b_tx_p[3]}]
# set_property PACKAGE_PIN K43 [get_ports {hmc_b_tx_p[4]}]
# set_property PACKAGE_PIN M48 [get_ports {hmc_b_rx_p[5]}]
# set_property PACKAGE_PIN M49 [get_ports {hmc_b_rx_n[5]}]
# set_property PACKAGE_PIN M43 [get_ports {hmc_b_tx_p[5]}]
# set_property PACKAGE_PIN M44 [get_ports {hmc_b_tx_n[5]}]
# set_property PACKAGE_PIN T43 [get_ports {hmc_b_tx_p[6]}]
# set_property PACKAGE_PIN R45 [get_ports {hmc_b_tx_p[7]}]
# set_property PACKAGE_PIN B43 [get_ports {hmc_b_tx_p[8]}]
# set_property PACKAGE_PIN E41 [get_ports {hmc_b_tx_p[9]}]
# set_property PACKAGE_PIN G50 [get_ports {hmc_b_rx_p[10]}]
# set_property PACKAGE_PIN G45 [get_ports {hmc_b_tx_p[10]}]
# set_property PACKAGE_PIN G51 [get_ports {hmc_b_rx_n[10]}]
# set_property PACKAGE_PIN G46 [get_ports {hmc_b_tx_n[10]}]
# set_property PACKAGE_PIN J45 [get_ports {hmc_b_tx_p[11]}]
# set_property PACKAGE_PIN C41 [get_ports {hmc_b_tx_p[12]}]
# set_property PACKAGE_PIN D43 [get_ports {hmc_b_tx_p[13]}]
# set_property PACKAGE_PIN F43 [get_ports {hmc_b_tx_p[14]}]
# set_property PACKAGE_PIN H43 [get_ports {hmc_b_tx_p[15]}]




set_property PACKAGE_PIN R10 [get_ports hmc_c_clk_n]
set_property PACKAGE_PIN R11 [get_ports hmc_c_clk_p]

set_property IOSTANDARD LVCMOS15 [get_ports hmc_c_ferr_n]
set_property PACKAGE_PIN J15 [get_ports hmc_c_ferr_n]
set_property PULLUP true [get_ports hmc_c_ferr_n]

set_property IOSTANDARD LVCMOS15 [get_ports hmc_c_p_rst_n]
set_property PACKAGE_PIN J18 [get_ports hmc_c_p_rst_n]



# set_property PACKAGE_PIN J1 [get_ports {hmc_c_rx_n[0]}]
# set_property PACKAGE_PIN C5 [get_ports {hmc_c_rx_n[1]}]
# set_property PACKAGE_PIN G1 [get_ports {hmc_c_rx_n[2]}]
# set_property PACKAGE_PIN D3 [get_ports {hmc_c_rx_n[3]}]
# set_property PACKAGE_PIN H3 [get_ports {hmc_c_rx_n[4]}]
# set_property PACKAGE_PIN F3 [get_ports {hmc_c_rx_n[5]}]
# set_property PACKAGE_PIN E5 [get_ports {hmc_c_rx_n[6]}]
# set_property PACKAGE_PIN E1 [get_ports {hmc_c_rx_n[7]}]
# set_property PACKAGE_PIN U1 [get_ports {hmc_c_rx_n[8]}]
# set_property PACKAGE_PIN T3 [get_ports {hmc_c_rx_n[9]}]
# set_property PACKAGE_PIN P3 [get_ports {hmc_c_rx_n[10]}]
# set_property PACKAGE_PIN L1 [get_ports {hmc_c_rx_n[11]}]
# set_property PACKAGE_PIN R1 [get_ports {hmc_c_rx_n[12]}]
# set_property PACKAGE_PIN N1 [get_ports {hmc_c_rx_n[13]}]
# set_property PACKAGE_PIN M3 [get_ports {hmc_c_rx_n[14]}]
# set_property PACKAGE_PIN K3 [get_ports {hmc_c_rx_n[15]}]
# set_property PACKAGE_PIN J2 [get_ports {hmc_c_rx_p[0]}]
# set_property PACKAGE_PIN C6 [get_ports {hmc_c_rx_p[1]}]
# set_property PACKAGE_PIN G2 [get_ports {hmc_c_rx_p[2]}]
# set_property PACKAGE_PIN D4 [get_ports {hmc_c_rx_p[3]}]
# set_property PACKAGE_PIN H4 [get_ports {hmc_c_rx_p[4]}]
# set_property PACKAGE_PIN F4 [get_ports {hmc_c_rx_p[5]}]
# set_property PACKAGE_PIN E6 [get_ports {hmc_c_rx_p[6]}]
# set_property PACKAGE_PIN E2 [get_ports {hmc_c_rx_p[7]}]
# set_property PACKAGE_PIN U2 [get_ports {hmc_c_rx_p[8]}]
# set_property PACKAGE_PIN T4 [get_ports {hmc_c_rx_p[9]}]
# set_property PACKAGE_PIN P4 [get_ports {hmc_c_rx_p[10]}]
# set_property PACKAGE_PIN L2 [get_ports {hmc_c_rx_p[11]}]
# set_property PACKAGE_PIN R2 [get_ports {hmc_c_rx_p[12]}]
# set_property PACKAGE_PIN N2 [get_ports {hmc_c_rx_p[13]}]
# set_property PACKAGE_PIN M4 [get_ports {hmc_c_rx_p[14]}]
# set_property PACKAGE_PIN K4 [get_ports {hmc_c_rx_p[15]}]




set_property IOSTANDARD LVCMOS15 [get_ports hmc_c_scl]
set_property PACKAGE_PIN J16 [get_ports hmc_c_scl]
set_property IOSTANDARD LVCMOS15 [get_ports hmc_c_sda]
set_property PACKAGE_PIN J19 [get_ports hmc_c_sda]




# set_property PACKAGE_PIN J6 [get_ports {hmc_c_tx_n[0]}]
# set_property PACKAGE_PIN E10 [get_ports {hmc_c_tx_n[1]}]
# set_property PACKAGE_PIN G6 [get_ports {hmc_c_tx_n[2]}]
# set_property PACKAGE_PIN B8 [get_ports {hmc_c_tx_n[3]}]
# set_property PACKAGE_PIN H8 [get_ports {hmc_c_tx_n[4]}]
# set_property PACKAGE_PIN F8 [get_ports {hmc_c_tx_n[5]}]
# set_property PACKAGE_PIN C10 [get_ports {hmc_c_tx_n[6]}]
# set_property PACKAGE_PIN D8 [get_ports {hmc_c_tx_n[7]}]
# set_property PACKAGE_PIN U6 [get_ports {hmc_c_tx_n[8]}]
# set_property PACKAGE_PIN T8 [get_ports {hmc_c_tx_n[9]}]
# set_property PACKAGE_PIN P8 [get_ports {hmc_c_tx_n[10]}]
# set_property PACKAGE_PIN L6 [get_ports {hmc_c_tx_n[11]}]
# set_property PACKAGE_PIN R6 [get_ports {hmc_c_tx_n[12]}]
# set_property PACKAGE_PIN N6 [get_ports {hmc_c_tx_n[13]}]
# set_property PACKAGE_PIN M8 [get_ports {hmc_c_tx_n[14]}]
# set_property PACKAGE_PIN K8 [get_ports {hmc_c_tx_n[15]}]
# set_property PACKAGE_PIN J7 [get_ports {hmc_c_tx_p[0]}]
# set_property PACKAGE_PIN E11 [get_ports {hmc_c_tx_p[1]}]
# set_property PACKAGE_PIN G7 [get_ports {hmc_c_tx_p[2]}]
# set_property PACKAGE_PIN B9 [get_ports {hmc_c_tx_p[3]}]
# set_property PACKAGE_PIN H9 [get_ports {hmc_c_tx_p[4]}]
# set_property PACKAGE_PIN F9 [get_ports {hmc_c_tx_p[5]}]
# set_property PACKAGE_PIN C11 [get_ports {hmc_c_tx_p[6]}]
# set_property PACKAGE_PIN D9 [get_ports {hmc_c_tx_p[7]}]
# set_property PACKAGE_PIN U7 [get_ports {hmc_c_tx_p[8]}]
# set_property PACKAGE_PIN T9 [get_ports {hmc_c_tx_p[9]}]
# set_property PACKAGE_PIN P9 [get_ports {hmc_c_tx_p[10]}]
# set_property PACKAGE_PIN L7 [get_ports {hmc_c_tx_p[11]}]
# set_property PACKAGE_PIN R7 [get_ports {hmc_c_tx_p[12]}]
# set_property PACKAGE_PIN N7 [get_ports {hmc_c_tx_p[13]}]
# set_property PACKAGE_PIN M9 [get_ports {hmc_c_tx_p[14]}]
# set_property PACKAGE_PIN K9 [get_ports {hmc_c_tx_p[15]}]




set_property PACKAGE_PIN AE10 [get_ports hmc_d_clk_n]
set_property PACKAGE_PIN AE11 [get_ports hmc_d_clk_p]

set_property IOSTANDARD LVCMOS15 [get_ports hmc_d_ferr_n]
set_property PACKAGE_PIN P15 [get_ports hmc_d_ferr_n]
set_property PULLUP true [get_ports hmc_d_ferr_n]

set_property IOSTANDARD LVCMOS15 [get_ports hmc_d_p_rst_n]
set_property PACKAGE_PIN R15 [get_ports hmc_d_p_rst_n]



# set_property PACKAGE_PIN AB3 [get_ports {hmc_d_rx_n[0]}]
# set_property PACKAGE_PIN AC1 [get_ports {hmc_d_rx_n[1]}]
# set_property PACKAGE_PIN Y3 [get_ports {hmc_d_rx_n[2]}]
# set_property PACKAGE_PIN W1 [get_ports {hmc_d_rx_n[3]}]
# set_property PACKAGE_PIN AG1 [get_ports {hmc_d_rx_n[4]}]
# set_property PACKAGE_PIN AE1 [get_ports {hmc_d_rx_n[5]}]
# set_property PACKAGE_PIN AA1 [get_ports {hmc_d_rx_n[6]}]
# set_property PACKAGE_PIN V3 [get_ports {hmc_d_rx_n[7]}]
# set_property PACKAGE_PIN AK3 [get_ports {hmc_d_rx_n[8]}]
# set_property PACKAGE_PIN AH3 [get_ports {hmc_d_rx_n[9]}]
# set_property PACKAGE_PIN AF3 [get_ports {hmc_d_rx_n[10]}]
# set_property PACKAGE_PIN AD3 [get_ports {hmc_d_rx_n[11]}]
# set_property PACKAGE_PIN AN1 [get_ports {hmc_d_rx_n[12]}]
# set_property PACKAGE_PIN AM3 [get_ports {hmc_d_rx_n[13]}]
# set_property PACKAGE_PIN AL1 [get_ports {hmc_d_rx_n[14]}]
# set_property PACKAGE_PIN AJ1 [get_ports {hmc_d_rx_n[15]}]
# set_property PACKAGE_PIN AB4 [get_ports {hmc_d_rx_p[0]}]
# set_property PACKAGE_PIN AC2 [get_ports {hmc_d_rx_p[1]}]
# set_property PACKAGE_PIN Y4 [get_ports {hmc_d_rx_p[2]}]
# set_property PACKAGE_PIN W2 [get_ports {hmc_d_rx_p[3]}]
# set_property PACKAGE_PIN AG2 [get_ports {hmc_d_rx_p[4]}]
# set_property PACKAGE_PIN AE2 [get_ports {hmc_d_rx_p[5]}]
# set_property PACKAGE_PIN AA2 [get_ports {hmc_d_rx_p[6]}]
# set_property PACKAGE_PIN V4 [get_ports {hmc_d_rx_p[7]}]
# set_property PACKAGE_PIN AK4 [get_ports {hmc_d_rx_p[8]}]
# set_property PACKAGE_PIN AH4 [get_ports {hmc_d_rx_p[9]}]
# set_property PACKAGE_PIN AF4 [get_ports {hmc_d_rx_p[10]}]
# set_property PACKAGE_PIN AD4 [get_ports {hmc_d_rx_p[11]}]
# set_property PACKAGE_PIN AN2 [get_ports {hmc_d_rx_p[12]}]
# set_property PACKAGE_PIN AM4 [get_ports {hmc_d_rx_p[13]}]
# set_property PACKAGE_PIN AL2 [get_ports {hmc_d_rx_p[14]}]
# set_property PACKAGE_PIN AJ2 [get_ports {hmc_d_rx_p[15]}]




set_property IOSTANDARD LVCMOS15 [get_ports hmc_d_scl]
set_property PACKAGE_PIN U15 [get_ports hmc_d_scl]
set_property IOSTANDARD LVCMOS15 [get_ports hmc_d_sda]
set_property PACKAGE_PIN T15 [get_ports hmc_d_sda]




# set_property PACKAGE_PIN AB8 [get_ports {hmc_d_tx_n[0]}]
# set_property PACKAGE_PIN AC6 [get_ports {hmc_d_tx_n[1]}]
# set_property PACKAGE_PIN Y8 [get_ports {hmc_d_tx_n[2]}]
# set_property PACKAGE_PIN W6 [get_ports {hmc_d_tx_n[3]}]
# set_property PACKAGE_PIN AG6 [get_ports {hmc_d_tx_n[4]}]
# set_property PACKAGE_PIN AE6 [get_ports {hmc_d_tx_n[5]}]
# set_property PACKAGE_PIN AA6 [get_ports {hmc_d_tx_n[6]}]
# set_property PACKAGE_PIN V8 [get_ports {hmc_d_tx_n[7]}]
# set_property PACKAGE_PIN AK8 [get_ports {hmc_d_tx_n[8]}]
# set_property PACKAGE_PIN AH8 [get_ports {hmc_d_tx_n[9]}]
# set_property PACKAGE_PIN AF8 [get_ports {hmc_d_tx_n[10]}]
# set_property PACKAGE_PIN AD8 [get_ports {hmc_d_tx_n[11]}]
# set_property PACKAGE_PIN AN6 [get_ports {hmc_d_tx_n[12]}]
# set_property PACKAGE_PIN AM8 [get_ports {hmc_d_tx_n[13]}]
# set_property PACKAGE_PIN AL6 [get_ports {hmc_d_tx_n[14]}]
# set_property PACKAGE_PIN AJ6 [get_ports {hmc_d_tx_n[15]}]
# set_property PACKAGE_PIN AB9 [get_ports {hmc_d_tx_p[0]}]
# set_property PACKAGE_PIN AC7 [get_ports {hmc_d_tx_p[1]}]
# set_property PACKAGE_PIN Y9 [get_ports {hmc_d_tx_p[2]}]
# set_property PACKAGE_PIN W7 [get_ports {hmc_d_tx_p[3]}]
# set_property PACKAGE_PIN AG7 [get_ports {hmc_d_tx_p[4]}]
# set_property PACKAGE_PIN AE7 [get_ports {hmc_d_tx_p[5]}]
# set_property PACKAGE_PIN AA7 [get_ports {hmc_d_tx_p[6]}]
# set_property PACKAGE_PIN V9 [get_ports {hmc_d_tx_p[7]}]
# set_property PACKAGE_PIN AK9 [get_ports {hmc_d_tx_p[8]}]
# set_property PACKAGE_PIN AH9 [get_ports {hmc_d_tx_p[9]}]
# set_property PACKAGE_PIN AF9 [get_ports {hmc_d_tx_p[10]}]
# set_property PACKAGE_PIN AD9 [get_ports {hmc_d_tx_p[11]}]
# set_property PACKAGE_PIN AN7 [get_ports {hmc_d_tx_p[12]}]
# set_property PACKAGE_PIN AM9 [get_ports {hmc_d_tx_p[13]}]
# set_property PACKAGE_PIN AL7 [get_ports {hmc_d_tx_p[14]}]
# set_property PACKAGE_PIN AJ7 [get_ports {hmc_d_tx_p[15]}]




set_property PACKAGE_PIN F23 [get_ports last_board]
set_property IOSTANDARD LVCMOS18 [get_ports last_board]

set_property PACKAGE_PIN B22 [get_ports led_cs]
set_property PACKAGE_PIN C23 [get_ports led_din]
set_property PACKAGE_PIN A23 [get_ports led_dout]
set_property PACKAGE_PIN A22 [get_ports led_sclk]
set_property IOSTANDARD LVCMOS18 [get_ports led_cs]
set_property IOSTANDARD LVCMOS18 [get_ports led_din]
set_property IOSTANDARD LVCMOS18 [get_ports led_dout]
set_property IOSTANDARD LVCMOS18 [get_ports led_sclk]


set_property PACKAGE_PIN AY39 [get_ports {mbo_a_clk_n[0]}]
set_property PACKAGE_PIN BB39 [get_ports {mbo_a_clk_n[1]}]
set_property PACKAGE_PIN BD39 [get_ports {mbo_a_clk_n[2]}]
set_property PACKAGE_PIN AY40 [get_ports {mbo_a_clk_p[0]}]
set_property PACKAGE_PIN BB40 [get_ports {mbo_a_clk_p[1]}]
set_property PACKAGE_PIN BD40 [get_ports {mbo_a_clk_p[2]}]
set_property PACKAGE_PIN BL28 [get_ports mbo_a_int_n]
set_property IOSTANDARD LVCMOS18 [get_ports mbo_a_int_n]
set_property PACKAGE_PIN BL30 [get_ports mbo_a_modprs_rx_n]
set_property IOSTANDARD LVCMOS18 [get_ports mbo_a_modprs_rx_n]
set_property PACKAGE_PIN BK30 [get_ports mbo_a_modprs_tx_n]
set_property IOSTANDARD LVCMOS18 [get_ports mbo_a_modprs_tx_n]
set_property PACKAGE_PIN BK28 [get_ports mbo_a_reset]
set_property IOSTANDARD LVCMOS18 [get_ports mbo_a_reset]

set_property PACKAGE_PIN BF49 [get_ports {mbo_a_rx_n[0]}]
set_property PACKAGE_PIN BF35 [get_ports {mbo_a_rx_n[1]}]
set_property PACKAGE_PIN BH35 [get_ports {mbo_a_rx_n[2]}]
set_property PACKAGE_PIN BH49 [get_ports {mbo_a_rx_n[3]}]

#:
set_property PACKAGE_PIN BG32 [get_ports {mbo_a_rx_n[4]}]

set_property PACKAGE_PIN BG47 [get_ports {mbo_a_rx_n[5]}]
set_property PACKAGE_PIN BJ33 [get_ports {mbo_a_rx_n[6]}]
set_property PACKAGE_PIN BG50 [get_ports {mbo_a_rx_n[7]}]
set_property PACKAGE_PIN BL33 [get_ports {mbo_a_rx_n[8]}]
set_property PACKAGE_PIN BJ47 [get_ports {mbo_a_rx_n[9]}]
set_property PACKAGE_PIN BK35 [get_ports {mbo_a_rx_n[10]}]
set_property PACKAGE_PIN BL47 [get_ports {mbo_a_rx_n[11]}]
set_property PACKAGE_PIN BF48 [get_ports {mbo_a_rx_p[0]}]
set_property PACKAGE_PIN BF34 [get_ports {mbo_a_rx_p[1]}]
set_property PACKAGE_PIN BH34 [get_ports {mbo_a_rx_p[2]}]
set_property PACKAGE_PIN BH48 [get_ports {mbo_a_rx_p[3]}]

#:
set_property PACKAGE_PIN BG33 [get_ports {mbo_a_rx_p[4]}]

set_property PACKAGE_PIN BG46 [get_ports {mbo_a_rx_p[5]}]
set_property PACKAGE_PIN BJ32 [get_ports {mbo_a_rx_p[6]}]
set_property PACKAGE_PIN BG51 [get_ports {mbo_a_rx_p[7]}]
set_property PACKAGE_PIN BL32 [get_ports {mbo_a_rx_p[8]}]
set_property PACKAGE_PIN BJ46 [get_ports {mbo_a_rx_p[9]}]
set_property PACKAGE_PIN BK34 [get_ports {mbo_a_rx_p[10]}]
set_property PACKAGE_PIN BL46 [get_ports {mbo_a_rx_p[11]}]
set_property PACKAGE_PIN BF44 [get_ports {mbo_a_tx_n[0]}]
set_property PACKAGE_PIN BF40 [get_ports {mbo_a_tx_n[1]}]
set_property PACKAGE_PIN BG38 [get_ports {mbo_a_tx_n[2]}]
set_property PACKAGE_PIN BG42 [get_ports {mbo_a_tx_n[3]}]
set_property PACKAGE_PIN BH40 [get_ports {mbo_a_tx_n[4]}]
set_property PACKAGE_PIN BH44 [get_ports {mbo_a_tx_n[5]}]
set_property PACKAGE_PIN BJ38 [get_ports {mbo_a_tx_n[6]}]
set_property PACKAGE_PIN BJ42 [get_ports {mbo_a_tx_n[7]}]
set_property PACKAGE_PIN BK40 [get_ports {mbo_a_tx_n[8]}]
set_property PACKAGE_PIN BK44 [get_ports {mbo_a_tx_n[9]}]
set_property PACKAGE_PIN BL38 [get_ports {mbo_a_tx_n[10]}]
set_property PACKAGE_PIN BL42 [get_ports {mbo_a_tx_n[11]}]
set_property PACKAGE_PIN BF43 [get_ports {mbo_a_tx_p[0]}]
set_property PACKAGE_PIN BF39 [get_ports {mbo_a_tx_p[1]}]
set_property PACKAGE_PIN BG37 [get_ports {mbo_a_tx_p[2]}]
set_property PACKAGE_PIN BG41 [get_ports {mbo_a_tx_p[3]}]
set_property PACKAGE_PIN BH39 [get_ports {mbo_a_tx_p[4]}]
set_property PACKAGE_PIN BH43 [get_ports {mbo_a_tx_p[5]}]
set_property PACKAGE_PIN BJ37 [get_ports {mbo_a_tx_p[6]}]
set_property PACKAGE_PIN BJ41 [get_ports {mbo_a_tx_p[7]}]
set_property PACKAGE_PIN BK39 [get_ports {mbo_a_tx_p[8]}]
set_property PACKAGE_PIN BK43 [get_ports {mbo_a_tx_p[9]}]
set_property PACKAGE_PIN BL37 [get_ports {mbo_a_tx_p[10]}]
set_property PACKAGE_PIN BL41 [get_ports {mbo_a_tx_p[11]}]

set_property PACKAGE_PIN AV40 [get_ports {mbo_b_clk_n[0]}]
set_property PACKAGE_PIN AT40 [get_ports {mbo_b_clk_n[1]}]
set_property PACKAGE_PIN AP40 [get_ports {mbo_b_clk_n[2]}]
set_property PACKAGE_PIN AV39 [get_ports {mbo_b_clk_p[0]}]
set_property PACKAGE_PIN AT39 [get_ports {mbo_b_clk_p[1]}]
set_property PACKAGE_PIN AP39 [get_ports {mbo_b_clk_p[2]}]
set_property PACKAGE_PIN BJ29 [get_ports mbo_b_int_n]
set_property IOSTANDARD LVCMOS18 [get_ports mbo_b_int_n]
set_property PACKAGE_PIN BJ28 [get_ports mbo_b_modprs_rx_n]
set_property IOSTANDARD LVCMOS18 [get_ports mbo_b_modprs_rx_n]
set_property PACKAGE_PIN C22 [get_ports mbo_b_modprs_tx_n]
set_property IOSTANDARD LVCMOS18 [get_ports mbo_b_modprs_tx_n]
set_property PACKAGE_PIN BK27 [get_ports mbo_b_reset]
set_property IOSTANDARD LVCMOS18 [get_ports mbo_b_reset]
set_property PACKAGE_PIN AR51 [get_ports {mbo_b_rx_n[0]}]
set_property PACKAGE_PIN AP49 [get_ports {mbo_b_rx_n[1]}]
set_property PACKAGE_PIN AT49 [get_ports {mbo_b_rx_n[2]}]
set_property PACKAGE_PIN AU51 [get_ports {mbo_b_rx_n[3]}]
set_property PACKAGE_PIN AV49 [get_ports {mbo_b_rx_n[4]}]
set_property PACKAGE_PIN AW51 [get_ports {mbo_b_rx_n[5]}]
set_property PACKAGE_PIN AY49 [get_ports {mbo_b_rx_n[6]}]
set_property PACKAGE_PIN BA51 [get_ports {mbo_b_rx_n[7]}]
set_property PACKAGE_PIN BB49 [get_ports {mbo_b_rx_n[8]}]
set_property PACKAGE_PIN BC51 [get_ports {mbo_b_rx_n[9]}]
set_property PACKAGE_PIN BD49 [get_ports {mbo_b_rx_n[10]}]
set_property PACKAGE_PIN BE51 [get_ports {mbo_b_rx_n[11]}]
set_property PACKAGE_PIN AR50 [get_ports {mbo_b_rx_p[0]}]
set_property PACKAGE_PIN AP48 [get_ports {mbo_b_rx_p[1]}]
set_property PACKAGE_PIN AT48 [get_ports {mbo_b_rx_p[2]}]
set_property PACKAGE_PIN AU50 [get_ports {mbo_b_rx_p[3]}]
set_property PACKAGE_PIN AV48 [get_ports {mbo_b_rx_p[4]}]
set_property PACKAGE_PIN AW50 [get_ports {mbo_b_rx_p[5]}]
set_property PACKAGE_PIN AY48 [get_ports {mbo_b_rx_p[6]}]
set_property PACKAGE_PIN BA50 [get_ports {mbo_b_rx_p[7]}]
set_property PACKAGE_PIN BB48 [get_ports {mbo_b_rx_p[8]}]
set_property PACKAGE_PIN BC50 [get_ports {mbo_b_rx_p[9]}]
set_property PACKAGE_PIN BD48 [get_ports {mbo_b_rx_p[10]}]
set_property PACKAGE_PIN BE50 [get_ports {mbo_b_rx_p[11]}]
set_property PACKAGE_PIN AW46 [get_ports {mbo_b_tx_n[0]}]
set_property PACKAGE_PIN AP44 [get_ports {mbo_b_tx_n[1]}]
set_property PACKAGE_PIN AT44 [get_ports {mbo_b_tx_n[2]}]
set_property PACKAGE_PIN AU46 [get_ports {mbo_b_tx_n[3]}]
set_property PACKAGE_PIN AV44 [get_ports {mbo_b_tx_n[4]}]
set_property PACKAGE_PIN AR46 [get_ports {mbo_b_tx_n[5]}]
set_property PACKAGE_PIN AY44 [get_ports {mbo_b_tx_n[6]}]
set_property PACKAGE_PIN BA46 [get_ports {mbo_b_tx_n[7]}]
set_property PACKAGE_PIN BB44 [get_ports {mbo_b_tx_n[8]}]
set_property PACKAGE_PIN BC46 [get_ports {mbo_b_tx_n[9]}]
set_property PACKAGE_PIN BD44 [get_ports {mbo_b_tx_n[10]}]
set_property PACKAGE_PIN BE46 [get_ports {mbo_b_tx_n[11]}]
set_property PACKAGE_PIN AW45 [get_ports {mbo_b_tx_p[0]}]
set_property PACKAGE_PIN AP43 [get_ports {mbo_b_tx_p[1]}]
set_property PACKAGE_PIN AT43 [get_ports {mbo_b_tx_p[2]}]
set_property PACKAGE_PIN AU45 [get_ports {mbo_b_tx_p[3]}]
set_property PACKAGE_PIN AV43 [get_ports {mbo_b_tx_p[4]}]
set_property PACKAGE_PIN AR45 [get_ports {mbo_b_tx_p[5]}]
set_property PACKAGE_PIN AY43 [get_ports {mbo_b_tx_p[6]}]
set_property PACKAGE_PIN BA45 [get_ports {mbo_b_tx_p[7]}]
set_property PACKAGE_PIN BB43 [get_ports {mbo_b_tx_p[8]}]
set_property PACKAGE_PIN BC45 [get_ports {mbo_b_tx_p[9]}]
set_property PACKAGE_PIN BD43 [get_ports {mbo_b_tx_p[10]}]
set_property PACKAGE_PIN BE45 [get_ports {mbo_b_tx_p[11]}]

set_property PACKAGE_PIN BD12 [get_ports {mbo_c_clk_n[0]}]
set_property PACKAGE_PIN BB12 [get_ports {mbo_c_clk_n[1]}]
set_property PACKAGE_PIN AY12 [get_ports {mbo_c_clk_n[2]}]
set_property PACKAGE_PIN BD13 [get_ports {mbo_c_clk_p[0]}]
set_property PACKAGE_PIN BB13 [get_ports {mbo_c_clk_p[1]}]
set_property PACKAGE_PIN AY13 [get_ports {mbo_c_clk_p[2]}]
set_property PACKAGE_PIN BL22 [get_ports mbo_c_int_n]
set_property IOSTANDARD LVCMOS18 [get_ports mbo_c_int_n]
set_property PACKAGE_PIN BK22 [get_ports mbo_c_modprs_rx_n]
set_property IOSTANDARD LVCMOS18 [get_ports mbo_c_modprs_rx_n]
set_property PACKAGE_PIN BL23 [get_ports mbo_c_modprs_tx_n]
set_property IOSTANDARD LVCMOS18 [get_ports mbo_c_modprs_tx_n]
set_property PACKAGE_PIN BL24 [get_ports mbo_c_reset]
set_property IOSTANDARD LVCMOS18 [get_ports mbo_c_reset]
set_property PACKAGE_PIN BL19 [get_ports {mbo_c_rx_n[0]}]
set_property PACKAGE_PIN BG19 [get_ports {mbo_c_rx_n[1]}]
set_property PACKAGE_PIN BK17 [get_ports {mbo_c_rx_n[2]}]
set_property PACKAGE_PIN BJ19 [get_ports {mbo_c_rx_n[3]}]
set_property PACKAGE_PIN BH17 [get_ports {mbo_c_rx_n[4]}]
set_property PACKAGE_PIN BF17 [get_ports {mbo_c_rx_n[5]}]
set_property PACKAGE_PIN BL5 [get_ports {mbo_c_rx_n[6]}]
set_property PACKAGE_PIN BJ5 [get_ports {mbo_c_rx_n[7]}]
set_property PACKAGE_PIN BH3 [get_ports {mbo_c_rx_n[8]}]
set_property PACKAGE_PIN BG5 [get_ports {mbo_c_rx_n[9]}]
set_property PACKAGE_PIN BG1 [get_ports {mbo_c_rx_n[10]}]
set_property PACKAGE_PIN BF3 [get_ports {mbo_c_rx_n[11]}]
set_property PACKAGE_PIN BL20 [get_ports {mbo_c_rx_p[0]}]
set_property PACKAGE_PIN BG20 [get_ports {mbo_c_rx_p[1]}]
set_property PACKAGE_PIN BK18 [get_ports {mbo_c_rx_p[2]}]
set_property PACKAGE_PIN BJ20 [get_ports {mbo_c_rx_p[3]}]
set_property PACKAGE_PIN BH18 [get_ports {mbo_c_rx_p[4]}]
set_property PACKAGE_PIN BF18 [get_ports {mbo_c_rx_p[5]}]
set_property PACKAGE_PIN BL6 [get_ports {mbo_c_rx_p[6]}]
set_property PACKAGE_PIN BJ6 [get_ports {mbo_c_rx_p[7]}]
set_property PACKAGE_PIN BH4 [get_ports {mbo_c_rx_p[8]}]
set_property PACKAGE_PIN BG6 [get_ports {mbo_c_rx_p[9]}]
set_property PACKAGE_PIN BG2 [get_ports {mbo_c_rx_p[10]}]
set_property PACKAGE_PIN BF4 [get_ports {mbo_c_rx_p[11]}]

#:
set_property PACKAGE_PIN BK13 [get_ports {mbo_c_tx_n[0]}]

#:
set_property PACKAGE_PIN BH13 [get_ports {mbo_c_tx_n[1]}]

set_property PACKAGE_PIN BL14 [get_ports {mbo_c_tx_n[2]}]
set_property PACKAGE_PIN BJ14 [get_ports {mbo_c_tx_n[3]}]
set_property PACKAGE_PIN BG14 [get_ports {mbo_c_tx_n[4]}]
set_property PACKAGE_PIN BF12 [get_ports {mbo_c_tx_n[5]}]
set_property PACKAGE_PIN BL10 [get_ports {mbo_c_tx_n[6]}]
set_property PACKAGE_PIN BK8 [get_ports {mbo_c_tx_n[7]}]
set_property PACKAGE_PIN BG10 [get_ports {mbo_c_tx_n[8]}]
set_property PACKAGE_PIN BH8 [get_ports {mbo_c_tx_n[9]}]
set_property PACKAGE_PIN BJ10 [get_ports {mbo_c_tx_n[10]}]
set_property PACKAGE_PIN BF8 [get_ports {mbo_c_tx_n[11]}]

#:
set_property PACKAGE_PIN BK12 [get_ports {mbo_c_tx_p[0]}]

#:
set_property PACKAGE_PIN BH12 [get_ports {mbo_c_tx_p[1]}]

set_property PACKAGE_PIN BL15 [get_ports {mbo_c_tx_p[2]}]
set_property PACKAGE_PIN BJ15 [get_ports {mbo_c_tx_p[3]}]
set_property PACKAGE_PIN BG15 [get_ports {mbo_c_tx_p[4]}]
set_property PACKAGE_PIN BF13 [get_ports {mbo_c_tx_p[5]}]
set_property PACKAGE_PIN BL11 [get_ports {mbo_c_tx_p[6]}]
set_property PACKAGE_PIN BK9 [get_ports {mbo_c_tx_p[7]}]
set_property PACKAGE_PIN BG11 [get_ports {mbo_c_tx_p[8]}]
set_property PACKAGE_PIN BH9 [get_ports {mbo_c_tx_p[9]}]
set_property PACKAGE_PIN BJ11 [get_ports {mbo_c_tx_p[10]}]
set_property PACKAGE_PIN BF9 [get_ports {mbo_c_tx_p[11]}]

set_property PACKAGE_PIN AW41 [get_ports {mbo_clk_g_n[0]}]
set_property PACKAGE_PIN AN41 [get_ports {mbo_clk_g_n[1]}]
set_property PACKAGE_PIN BA10 [get_ports {mbo_clk_g_n[2]}]
set_property PACKAGE_PIN AW42 [get_ports {mbo_clk_g_p[0]}]
set_property PACKAGE_PIN AN42 [get_ports {mbo_clk_g_p[1]}]
set_property PACKAGE_PIN BA11 [get_ports {mbo_clk_g_p[2]}]

set_property PACKAGE_PIN BL25 [get_ports optics_l_reset_n]
set_property PACKAGE_PIN BE20 [get_ports optics_l_scl]
set_property PACKAGE_PIN BE21 [get_ports optics_l_sda]
set_property PACKAGE_PIN BL27 [get_ports optics_r_reset_n]
set_property PACKAGE_PIN BD36 [get_ports optics_r_scl]
set_property PACKAGE_PIN BD37 [get_ports optics_r_sda]
set_property IOSTANDARD LVCMOS18 [get_ports optics_l_reset_n]
set_property IOSTANDARD LVCMOS18 [get_ports optics_l_scl]
set_property IOSTANDARD LVCMOS18 [get_ports optics_l_sda]
set_property IOSTANDARD LVCMOS18 [get_ports optics_r_reset_n]
set_property IOSTANDARD LVCMOS18 [get_ports optics_r_scl]
set_property IOSTANDARD LVCMOS18 [get_ports optics_r_sda]

set_property PACKAGE_PIN BB34 [get_ports pmbus_alert]
set_property PACKAGE_PIN AY37 [get_ports pmbus_sda]
set_property PACKAGE_PIN BA37 [get_ports pmbus_sdc]
set_property IOSTANDARD LVCMOS18 [get_ports pmbus_alert]
set_property IOSTANDARD LVCMOS18 [get_ports pmbus_sda]
set_property IOSTANDARD LVCMOS18 [get_ports pmbus_sdc]

set_property PACKAGE_PIN B29 [get_ports ptp_clk_sel]
set_property IOSTANDARD LVCMOS18 [get_ports ptp_clk_sel]
set_property PACKAGE_PIN D29 [get_ports ptp_din]
set_property IOSTANDARD LVCMOS18 [get_ports ptp_din]
set_property PACKAGE_PIN C28 [get_ports ptp_sclk]
set_property IOSTANDARD LVCMOS18 [get_ports ptp_sclk]
set_property PACKAGE_PIN F29 [get_ports {ptp_sync_n[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ptp_sync_n[0]}]
set_property PACKAGE_PIN G29 [get_ports {ptp_sync_n[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ptp_sync_n[1]}]

set_property PACKAGE_PIN L10 [get_ports qsfp_a_clk_n]
set_property PACKAGE_PIN L11 [get_ports qsfp_a_clk_p]
set_property PACKAGE_PIN E22 [get_ports qsfp_a_mod_prs_n]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp_a_mod_prs_n]
set_property PACKAGE_PIN F22 [get_ports qsfp_a_reset]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp_a_reset]

set_property PACKAGE_PIN C20 [get_ports {qsfp_a_rx_p[0]}]
set_property PACKAGE_PIN C19 [get_ports {qsfp_a_rx_n[0]}]
set_property PACKAGE_PIN C15 [get_ports {qsfp_a_tx_p[0]}]
set_property PACKAGE_PIN C14 [get_ports {qsfp_a_tx_n[0]}]
set_property PACKAGE_PIN B18 [get_ports {qsfp_a_rx_p[1]}]
set_property PACKAGE_PIN B17 [get_ports {qsfp_a_rx_n[1]}]
set_property PACKAGE_PIN A15 [get_ports {qsfp_a_tx_p[1]}]
set_property PACKAGE_PIN A14 [get_ports {qsfp_a_tx_n[1]}]
set_property PACKAGE_PIN A20 [get_ports {qsfp_a_rx_p[2]}]
set_property PACKAGE_PIN A19 [get_ports {qsfp_a_rx_n[2]}]
set_property PACKAGE_PIN B13 [get_ports {qsfp_a_tx_p[2]}]
set_property PACKAGE_PIN B12 [get_ports {qsfp_a_tx_n[2]}]
set_property PACKAGE_PIN A6 [get_ports {qsfp_a_rx_p[3]}]
set_property PACKAGE_PIN A5 [get_ports {qsfp_a_rx_n[3]}]
set_property PACKAGE_PIN A11 [get_ports {qsfp_a_tx_p[3]}]
set_property PACKAGE_PIN A10 [get_ports {qsfp_a_tx_n[3]}]

set_property PACKAGE_PIN AP12 [get_ports qsfp_b_clk_n]
set_property PACKAGE_PIN AP13 [get_ports qsfp_b_clk_p]
set_property PACKAGE_PIN BB22 [get_ports qsfp_b_mod_prs_n]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp_b_mod_prs_n]
set_property PACKAGE_PIN BC22 [get_ports qsfp_b_reset]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp_b_reset]

set_property PACKAGE_PIN AP3 [get_ports {qsfp_b_rx_n[0]}]
set_property PACKAGE_PIN AR1 [get_ports {qsfp_b_rx_n[1]}]
set_property PACKAGE_PIN AU1 [get_ports {qsfp_b_rx_n[2]}]
set_property PACKAGE_PIN AT3 [get_ports {qsfp_b_rx_n[3]}]
set_property PACKAGE_PIN AP4 [get_ports {qsfp_b_rx_p[0]}]
set_property PACKAGE_PIN AR2 [get_ports {qsfp_b_rx_p[1]}]
set_property PACKAGE_PIN AU2 [get_ports {qsfp_b_rx_p[2]}]
set_property PACKAGE_PIN AT4 [get_ports {qsfp_b_rx_p[3]}]
set_property PACKAGE_PIN AP8 [get_ports {qsfp_b_tx_n[0]}]
set_property PACKAGE_PIN AR6 [get_ports {qsfp_b_tx_n[1]}]
set_property PACKAGE_PIN AU6 [get_ports {qsfp_b_tx_n[2]}]
set_property PACKAGE_PIN AT8 [get_ports {qsfp_b_tx_n[3]}]
set_property PACKAGE_PIN AP9 [get_ports {qsfp_b_tx_p[0]}]
set_property PACKAGE_PIN AR7 [get_ports {qsfp_b_tx_p[1]}]
set_property PACKAGE_PIN AU7 [get_ports {qsfp_b_tx_p[2]}]
set_property PACKAGE_PIN AT9 [get_ports {qsfp_b_tx_p[3]}]

set_property PACKAGE_PIN AT12 [get_ports qsfp_c_clk_n]
set_property PACKAGE_PIN AT13 [get_ports qsfp_c_clk_p]
set_property PACKAGE_PIN AY23 [get_ports qsfp_c_mod_prs_n]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp_c_mod_prs_n]
set_property PACKAGE_PIN BA23 [get_ports qsfp_c_reset]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp_c_reset]

set_property PACKAGE_PIN AY3 [get_ports {qsfp_c_rx_n[0]}]
set_property PACKAGE_PIN BA1 [get_ports {qsfp_c_rx_n[1]}]
set_property PACKAGE_PIN AY4 [get_ports {qsfp_c_rx_p[0]}]
set_property PACKAGE_PIN BA2 [get_ports {qsfp_c_rx_p[1]}]
set_property PACKAGE_PIN AY8 [get_ports {qsfp_c_tx_n[0]}]
set_property PACKAGE_PIN BA6 [get_ports {qsfp_c_tx_n[1]}]
set_property PACKAGE_PIN AY9 [get_ports {qsfp_c_tx_p[0]}]
set_property PACKAGE_PIN BA7 [get_ports {qsfp_c_tx_p[1]}]
set_property PACKAGE_PIN AW2 [get_ports {qsfp_c_rx_p[2]}]
set_property PACKAGE_PIN AW1 [get_ports {qsfp_c_rx_n[2]}]
set_property PACKAGE_PIN AW7 [get_ports {qsfp_c_tx_p[2]}]
set_property PACKAGE_PIN AW6 [get_ports {qsfp_c_tx_n[2]}]
set_property PACKAGE_PIN AV4 [get_ports {qsfp_c_rx_p[3]}]
set_property PACKAGE_PIN AV3 [get_ports {qsfp_c_rx_n[3]}]
set_property PACKAGE_PIN AV9 [get_ports {qsfp_c_tx_p[3]}]
set_property PACKAGE_PIN AV8 [get_ports {qsfp_c_tx_n[3]}]

set_property PACKAGE_PIN K12 [get_ports {qsfp_clock_b_n[0]}]
set_property PACKAGE_PIN AN10 [get_ports {qsfp_clock_b_n[1]}]
set_property PACKAGE_PIN AR10 [get_ports {qsfp_clock_b_n[2]}]
set_property PACKAGE_PIN K13 [get_ports {qsfp_clock_b_p[0]}]
set_property PACKAGE_PIN AN11 [get_ports {qsfp_clock_b_p[1]}]
set_property PACKAGE_PIN AR11 [get_ports {qsfp_clock_b_p[2]}]

set_property PACKAGE_PIN B24 [get_ports qsfp_clock_sel]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp_clock_sel]

set_property PACKAGE_PIN AV12 [get_ports qsfp_d_clk_n]
set_property PACKAGE_PIN AV13 [get_ports qsfp_d_clk_p]
set_property PACKAGE_PIN AV24 [get_ports qsfp_d_mod_prs_n]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp_d_mod_prs_n]
set_property PACKAGE_PIN AW23 [get_ports qsfp_d_reset]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp_d_reset]

set_property PACKAGE_PIN BB3 [get_ports {qsfp_d_rx_n[0]}]
set_property PACKAGE_PIN BE1 [get_ports {qsfp_d_rx_n[1]}]
set_property PACKAGE_PIN BD3 [get_ports {qsfp_d_rx_n[3]}]
set_property PACKAGE_PIN BB4 [get_ports {qsfp_d_rx_p[0]}]
set_property PACKAGE_PIN BE2 [get_ports {qsfp_d_rx_p[1]}]
set_property PACKAGE_PIN BD4 [get_ports {qsfp_d_rx_p[3]}]
set_property PACKAGE_PIN BB8 [get_ports {qsfp_d_tx_n[0]}]
set_property PACKAGE_PIN BE6 [get_ports {qsfp_d_tx_n[1]}]
set_property PACKAGE_PIN BD8 [get_ports {qsfp_d_tx_n[3]}]
set_property PACKAGE_PIN BB9 [get_ports {qsfp_d_tx_p[0]}]
set_property PACKAGE_PIN BE7 [get_ports {qsfp_d_tx_p[1]}]
set_property PACKAGE_PIN BC2 [get_ports {qsfp_d_rx_p[2]}]
set_property PACKAGE_PIN BC1 [get_ports {qsfp_d_rx_n[2]}]
set_property PACKAGE_PIN BC7 [get_ports {qsfp_d_tx_p[2]}]
set_property PACKAGE_PIN BC6 [get_ports {qsfp_d_tx_n[2]}]
set_property PACKAGE_PIN BD9 [get_ports {qsfp_d_tx_p[3]}]

set_property PACKAGE_PIN BG22 [get_ports qsfp_int_n]
set_property IOSTANDARD LVCMOS18 [get_ports qsfp_int_n]

set_property PACKAGE_PIN A30 [get_ports serial_prom]
set_property IOSTANDARD LVCMOS18 [get_ports serial_prom]

set_property PACKAGE_PIN K40 [get_ports sfp_a_clk_n]
set_property PACKAGE_PIN K39 [get_ports sfp_a_clk_p]
set_property PACKAGE_PIN B30 [get_ports sfp_a_mod_abs]
set_property IOSTANDARD LVCMOS18 [get_ports sfp_a_mod_abs]
set_property PACKAGE_PIN D30 [get_ports sfp_a_tx_enable]
set_property IOSTANDARD LVCMOS18 [get_ports sfp_a_tx_enable]
set_property PACKAGE_PIN A46 [get_ports sfp_a_rx_p]
set_property PACKAGE_PIN A41 [get_ports sfp_a_tx_p]
set_property PACKAGE_PIN A47 [get_ports sfp_a_rx_n]
set_property PACKAGE_PIN A42 [get_ports sfp_a_tx_n]

set_property PACKAGE_PIN L42 [get_ports sfp_b_clk_n]
set_property PACKAGE_PIN L41 [get_ports sfp_b_clk_p]
set_property PACKAGE_PIN E30 [get_ports sfp_b_mod_abs]
set_property IOSTANDARD LVCMOS18 [get_ports sfp_b_mod_abs]
set_property PACKAGE_PIN F30 [get_ports sfp_b_tx_enable]
set_property IOSTANDARD LVCMOS18 [get_ports sfp_b_tx_enable]
set_property PACKAGE_PIN A32 [get_ports sfp_b_rx_p]
set_property PACKAGE_PIN B39 [get_ports sfp_b_tx_p]
set_property PACKAGE_PIN A33 [get_ports sfp_b_rx_n]
set_property PACKAGE_PIN B40 [get_ports sfp_b_tx_n]

set_property PACKAGE_PIN G30 [get_ports sfp_fault]
set_property IOSTANDARD LVCMOS18 [get_ports sfp_fault]

set_property PACKAGE_PIN BC33 [get_ports slave]
set_property IOSTANDARD LVCMOS18 [get_ports slave]

set_property PACKAGE_PIN BA22 [get_ports {spi_cs[1]}]
set_property PACKAGE_PIN BD18 [get_ports {spi_d[4]}]
set_property PACKAGE_PIN BD17 [get_ports {spi_d[5]}]
set_property PACKAGE_PIN BB17 [get_ports {spi_d[6]}]
set_property PACKAGE_PIN BC17 [get_ports {spi_d[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {spi_cs[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {spi_d[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {spi_d[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {spi_d[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {spi_d[7]}]

set_property PACKAGE_PIN BC37 [get_ports {version[0]}]
set_property PACKAGE_PIN BC36 [get_ports {version[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {version[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {version[1]}]


